#############################################################################
# Makefile for building: clothSim
# Generated by qmake (3.1) (Qt 5.9.5)
# Project:  clothSim.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile clothSim.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I../glm -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtOpenGL -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = clothSim1.0.0
DISTDIR = /home/jonathan/Documents/Univeristy/Animation\ and\ Simulation/Coursework3/clothSim/.tmp/clothSim1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -lGLU -lQt5OpenGL -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = Cartesian3.cpp \
		Cloth.cpp \
		GObject.cpp \
		main.cpp \
		MasterWidget.cpp \
		MousePick.cpp \
		PointMass.cpp \
		RenderWidget.cpp \
		Simulation.cpp \
		Spring.cpp \
		Wind.cpp moc_MasterWidget.cpp \
		moc_RenderWidget.cpp
OBJECTS       = Cartesian3.o \
		Cloth.o \
		GObject.o \
		main.o \
		MasterWidget.o \
		MousePick.o \
		PointMass.o \
		RenderWidget.o \
		Simulation.o \
		Spring.o \
		Wind.o \
		moc_MasterWidget.o \
		moc_RenderWidget.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		clothSim.pro camera.h \
		Cartesian3.h \
		Cloth.h \
		GObject.h \
		MasterWidget.h \
		matrix.h \
		MousePick.h \
		PointMass.h \
		RenderWidget.h \
		Simulation.h \
		Spring.h \
		Wind.h Cartesian3.cpp \
		Cloth.cpp \
		GObject.cpp \
		main.cpp \
		MasterWidget.cpp \
		MousePick.cpp \
		PointMass.cpp \
		RenderWidget.cpp \
		Simulation.cpp \
		Spring.cpp \
		Wind.cpp
QMAKE_TARGET  = clothSim
DESTDIR       = 
TARGET        = clothSim


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: clothSim.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		clothSim.pro \
		/usr/lib/x86_64-linux-gnu/libQt5OpenGL.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -o Makefile clothSim.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
clothSim.pro:
/usr/lib/x86_64-linux-gnu/libQt5OpenGL.prl:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile clothSim.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents camera.h Cartesian3.h Cloth.h GObject.h MasterWidget.h matrix.h MousePick.h PointMass.h RenderWidget.h Simulation.h Spring.h Wind.h $(DISTDIR)/
	$(COPY_FILE) --parents Cartesian3.cpp Cloth.cpp GObject.cpp main.cpp MasterWidget.cpp MousePick.cpp PointMass.cpp RenderWidget.cpp Simulation.cpp Spring.cpp Wind.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -Wall -W -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_MasterWidget.cpp moc_RenderWidget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_MasterWidget.cpp moc_RenderWidget.cpp
moc_MasterWidget.cpp: MasterWidget.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/home/jonathan/Documents/Univeristy/Animation and Simulation/Coursework3/clothSim' -I'/home/jonathan/Documents/Univeristy/Animation and Simulation/Coursework3/glm' -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include MasterWidget.h -o moc_MasterWidget.cpp

moc_RenderWidget.cpp: MousePick.h \
		Cartesian3.h \
		camera.h \
		../glm/glm.hpp \
		../glm/detail/_fixes.hpp \
		../glm/detail/setup.hpp \
		../glm/simd/platform.h \
		../glm/simd/neon.h \
		../glm/fwd.hpp \
		../glm/detail/qualifier.hpp \
		../glm/vec2.hpp \
		../glm/ext/vector_bool2.hpp \
		../glm/detail/type_vec2.hpp \
		../glm/detail/_swizzle.hpp \
		../glm/detail/_swizzle_func.hpp \
		../glm/detail/type_vec2.inl \
		../glm/detail/compute_vector_relational.hpp \
		../glm/ext/vector_bool2_precision.hpp \
		../glm/ext/vector_float2.hpp \
		../glm/ext/vector_float2_precision.hpp \
		../glm/ext/vector_double2.hpp \
		../glm/ext/vector_double2_precision.hpp \
		../glm/ext/vector_int2.hpp \
		../glm/ext/vector_int2_precision.hpp \
		../glm/ext/vector_uint2.hpp \
		../glm/ext/vector_uint2_precision.hpp \
		../glm/vec3.hpp \
		../glm/ext/vector_bool3.hpp \
		../glm/detail/type_vec3.hpp \
		../glm/detail/type_vec3.inl \
		../glm/ext/vector_bool3_precision.hpp \
		../glm/ext/vector_float3.hpp \
		../glm/ext/vector_float3_precision.hpp \
		../glm/ext/vector_double3.hpp \
		../glm/ext/vector_double3_precision.hpp \
		../glm/ext/vector_int3.hpp \
		../glm/ext/vector_int3_precision.hpp \
		../glm/ext/vector_uint3.hpp \
		../glm/ext/vector_uint3_precision.hpp \
		../glm/vec4.hpp \
		../glm/ext/vector_bool4.hpp \
		../glm/detail/type_vec4.hpp \
		../glm/detail/type_vec4.inl \
		../glm/detail/type_vec4_simd.inl \
		../glm/ext/vector_bool4_precision.hpp \
		../glm/ext/vector_float4.hpp \
		../glm/ext/vector_float4_precision.hpp \
		../glm/ext/vector_double4.hpp \
		../glm/ext/vector_double4_precision.hpp \
		../glm/ext/vector_int4.hpp \
		../glm/ext/vector_int4_precision.hpp \
		../glm/ext/vector_uint4.hpp \
		../glm/ext/vector_uint4_precision.hpp \
		../glm/mat2x2.hpp \
		../glm/ext/matrix_double2x2.hpp \
		../glm/detail/type_mat2x2.hpp \
		../glm/detail/type_mat2x2.inl \
		../glm/matrix.hpp \
		../glm/mat2x3.hpp \
		../glm/ext/matrix_double2x3.hpp \
		../glm/detail/type_mat2x3.hpp \
		../glm/detail/type_mat2x3.inl \
		../glm/ext/matrix_double2x3_precision.hpp \
		../glm/ext/matrix_float2x3.hpp \
		../glm/ext/matrix_float2x3_precision.hpp \
		../glm/mat2x4.hpp \
		../glm/ext/matrix_double2x4.hpp \
		../glm/detail/type_mat2x4.hpp \
		../glm/detail/type_mat2x4.inl \
		../glm/ext/matrix_double2x4_precision.hpp \
		../glm/ext/matrix_float2x4.hpp \
		../glm/ext/matrix_float2x4_precision.hpp \
		../glm/mat3x2.hpp \
		../glm/ext/matrix_double3x2.hpp \
		../glm/detail/type_mat3x2.hpp \
		../glm/detail/type_mat3x2.inl \
		../glm/ext/matrix_double3x2_precision.hpp \
		../glm/ext/matrix_float3x2.hpp \
		../glm/ext/matrix_float3x2_precision.hpp \
		../glm/mat3x3.hpp \
		../glm/ext/matrix_double3x3.hpp \
		../glm/detail/type_mat3x3.hpp \
		../glm/detail/type_mat3x3.inl \
		../glm/ext/matrix_double3x3_precision.hpp \
		../glm/ext/matrix_float3x3.hpp \
		../glm/ext/matrix_float3x3_precision.hpp \
		../glm/mat3x4.hpp \
		../glm/ext/matrix_double3x4.hpp \
		../glm/detail/type_mat3x4.hpp \
		../glm/detail/type_mat3x4.inl \
		../glm/ext/matrix_double3x4_precision.hpp \
		../glm/ext/matrix_float3x4.hpp \
		../glm/ext/matrix_float3x4_precision.hpp \
		../glm/mat4x2.hpp \
		../glm/ext/matrix_double4x2.hpp \
		../glm/detail/type_mat4x2.hpp \
		../glm/detail/type_mat4x2.inl \
		../glm/ext/matrix_double4x2_precision.hpp \
		../glm/ext/matrix_float4x2.hpp \
		../glm/ext/matrix_float4x2_precision.hpp \
		../glm/mat4x3.hpp \
		../glm/ext/matrix_double4x3.hpp \
		../glm/detail/type_mat4x3.hpp \
		../glm/detail/type_mat4x3.inl \
		../glm/ext/matrix_double4x3_precision.hpp \
		../glm/ext/matrix_float4x3.hpp \
		../glm/ext/matrix_float4x3_precision.hpp \
		../glm/mat4x4.hpp \
		../glm/ext/matrix_double4x4.hpp \
		../glm/detail/type_mat4x4.hpp \
		../glm/detail/type_mat4x4.inl \
		../glm/detail/type_mat4x4_simd.inl \
		../glm/ext/matrix_double4x4_precision.hpp \
		../glm/ext/matrix_float4x4.hpp \
		../glm/ext/matrix_float4x4_precision.hpp \
		../glm/detail/func_matrix.inl \
		../glm/geometric.hpp \
		../glm/detail/func_geometric.inl \
		../glm/exponential.hpp \
		../glm/detail/type_vec1.hpp \
		../glm/detail/type_vec1.inl \
		../glm/detail/func_exponential.inl \
		../glm/vector_relational.hpp \
		../glm/detail/func_vector_relational.inl \
		../glm/detail/func_vector_relational_simd.inl \
		../glm/detail/_vectorize.hpp \
		../glm/detail/func_exponential_simd.inl \
		../glm/simd/exponential.h \
		../glm/common.hpp \
		../glm/detail/func_common.inl \
		../glm/detail/compute_common.hpp \
		../glm/detail/func_common_simd.inl \
		../glm/simd/common.h \
		../glm/detail/func_geometric_simd.inl \
		../glm/simd/geometric.h \
		../glm/detail/func_matrix_simd.inl \
		../glm/simd/matrix.h \
		../glm/ext/matrix_double2x2_precision.hpp \
		../glm/ext/matrix_float2x2.hpp \
		../glm/ext/matrix_float2x2_precision.hpp \
		../glm/trigonometric.hpp \
		../glm/detail/func_trigonometric.inl \
		../glm/detail/func_trigonometric_simd.inl \
		../glm/packing.hpp \
		../glm/detail/func_packing.inl \
		../glm/detail/type_half.hpp \
		../glm/detail/type_half.inl \
		../glm/detail/func_packing_simd.inl \
		../glm/integer.hpp \
		../glm/detail/func_integer.inl \
		../glm/detail/func_integer_simd.inl \
		../glm/simd/integer.h \
		../glm/gtc/matrix_transform.hpp \
		../glm/ext/matrix_projection.hpp \
		../glm/gtc/constants.hpp \
		../glm/ext/scalar_constants.hpp \
		../glm/ext/scalar_constants.inl \
		../glm/gtc/constants.inl \
		../glm/ext/matrix_projection.inl \
		../glm/ext/matrix_clip_space.hpp \
		../glm/ext/matrix_clip_space.inl \
		../glm/ext/matrix_transform.hpp \
		../glm/gtc/matrix_transform.inl \
		../glm/gtc/type_ptr.hpp \
		../glm/gtc/quaternion.hpp \
		../glm/ext/vector_relational.hpp \
		../glm/ext/vector_relational.inl \
		../glm/detail/type_float.hpp \
		../glm/ext/quaternion_common.hpp \
		../glm/ext/quaternion_geometric.hpp \
		../glm/ext/quaternion_geometric.inl \
		../glm/ext/quaternion_common.inl \
		../glm/ext/quaternion_common_simd.inl \
		../glm/ext/quaternion_float.hpp \
		../glm/detail/type_quat.hpp \
		../glm/ext/quaternion_relational.hpp \
		../glm/ext/quaternion_relational.inl \
		../glm/detail/type_quat.inl \
		../glm/detail/type_quat_simd.inl \
		../glm/ext/quaternion_float_precision.hpp \
		../glm/ext/quaternion_double.hpp \
		../glm/ext/quaternion_double_precision.hpp \
		../glm/ext/quaternion_trigonometric.hpp \
		../glm/ext/quaternion_trigonometric.inl \
		../glm/ext/quaternion_transform.hpp \
		../glm/ext/quaternion_transform.inl \
		../glm/gtc/quaternion.inl \
		../glm/gtc/epsilon.hpp \
		../glm/gtc/epsilon.inl \
		../glm/gtc/quaternion_simd.inl \
		../glm/gtc/vec1.hpp \
		../glm/ext/vector_bool1.hpp \
		../glm/ext/vector_bool1_precision.hpp \
		../glm/ext/vector_float1.hpp \
		../glm/ext/vector_float1_precision.hpp \
		../glm/ext/vector_double1.hpp \
		../glm/ext/vector_double1_precision.hpp \
		../glm/ext/vector_int1.hpp \
		../glm/ext/vector_int1_precision.hpp \
		../glm/ext/vector_uint1.hpp \
		../glm/ext/vector_uint1_precision.hpp \
		../glm/gtc/type_ptr.inl \
		../glm/gtx/intersect.hpp \
		../glm/gtx/closest_point.hpp \
		../glm/gtx/closest_point.inl \
		../glm/gtx/vector_query.hpp \
		../glm/gtx/vector_query.inl \
		../glm/gtx/intersect.inl \
		MasterWidget.h \
		Simulation.h \
		Cloth.h \
		PointMass.h \
		Spring.h \
		Wind.h \
		RenderWidget.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/home/jonathan/Documents/Univeristy/Animation and Simulation/Coursework3/clothSim' -I'/home/jonathan/Documents/Univeristy/Animation and Simulation/Coursework3/glm' -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include RenderWidget.h -o moc_RenderWidget.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

Cartesian3.o: Cartesian3.cpp Cartesian3.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Cartesian3.o Cartesian3.cpp

Cloth.o: Cloth.cpp Cloth.h \
		Cartesian3.h \
		camera.h \
		../glm/glm.hpp \
		../glm/detail/_fixes.hpp \
		../glm/detail/setup.hpp \
		../glm/simd/platform.h \
		../glm/simd/neon.h \
		../glm/fwd.hpp \
		../glm/detail/qualifier.hpp \
		../glm/vec2.hpp \
		../glm/ext/vector_bool2.hpp \
		../glm/detail/type_vec2.hpp \
		../glm/detail/_swizzle.hpp \
		../glm/detail/_swizzle_func.hpp \
		../glm/detail/type_vec2.inl \
		../glm/detail/compute_vector_relational.hpp \
		../glm/ext/vector_bool2_precision.hpp \
		../glm/ext/vector_float2.hpp \
		../glm/ext/vector_float2_precision.hpp \
		../glm/ext/vector_double2.hpp \
		../glm/ext/vector_double2_precision.hpp \
		../glm/ext/vector_int2.hpp \
		../glm/ext/vector_int2_precision.hpp \
		../glm/ext/vector_uint2.hpp \
		../glm/ext/vector_uint2_precision.hpp \
		../glm/vec3.hpp \
		../glm/ext/vector_bool3.hpp \
		../glm/detail/type_vec3.hpp \
		../glm/detail/type_vec3.inl \
		../glm/ext/vector_bool3_precision.hpp \
		../glm/ext/vector_float3.hpp \
		../glm/ext/vector_float3_precision.hpp \
		../glm/ext/vector_double3.hpp \
		../glm/ext/vector_double3_precision.hpp \
		../glm/ext/vector_int3.hpp \
		../glm/ext/vector_int3_precision.hpp \
		../glm/ext/vector_uint3.hpp \
		../glm/ext/vector_uint3_precision.hpp \
		../glm/vec4.hpp \
		../glm/ext/vector_bool4.hpp \
		../glm/detail/type_vec4.hpp \
		../glm/detail/type_vec4.inl \
		../glm/detail/type_vec4_simd.inl \
		../glm/ext/vector_bool4_precision.hpp \
		../glm/ext/vector_float4.hpp \
		../glm/ext/vector_float4_precision.hpp \
		../glm/ext/vector_double4.hpp \
		../glm/ext/vector_double4_precision.hpp \
		../glm/ext/vector_int4.hpp \
		../glm/ext/vector_int4_precision.hpp \
		../glm/ext/vector_uint4.hpp \
		../glm/ext/vector_uint4_precision.hpp \
		../glm/mat2x2.hpp \
		../glm/ext/matrix_double2x2.hpp \
		../glm/detail/type_mat2x2.hpp \
		../glm/detail/type_mat2x2.inl \
		../glm/matrix.hpp \
		../glm/mat2x3.hpp \
		../glm/ext/matrix_double2x3.hpp \
		../glm/detail/type_mat2x3.hpp \
		../glm/detail/type_mat2x3.inl \
		../glm/ext/matrix_double2x3_precision.hpp \
		../glm/ext/matrix_float2x3.hpp \
		../glm/ext/matrix_float2x3_precision.hpp \
		../glm/mat2x4.hpp \
		../glm/ext/matrix_double2x4.hpp \
		../glm/detail/type_mat2x4.hpp \
		../glm/detail/type_mat2x4.inl \
		../glm/ext/matrix_double2x4_precision.hpp \
		../glm/ext/matrix_float2x4.hpp \
		../glm/ext/matrix_float2x4_precision.hpp \
		../glm/mat3x2.hpp \
		../glm/ext/matrix_double3x2.hpp \
		../glm/detail/type_mat3x2.hpp \
		../glm/detail/type_mat3x2.inl \
		../glm/ext/matrix_double3x2_precision.hpp \
		../glm/ext/matrix_float3x2.hpp \
		../glm/ext/matrix_float3x2_precision.hpp \
		../glm/mat3x3.hpp \
		../glm/ext/matrix_double3x3.hpp \
		../glm/detail/type_mat3x3.hpp \
		../glm/detail/type_mat3x3.inl \
		../glm/ext/matrix_double3x3_precision.hpp \
		../glm/ext/matrix_float3x3.hpp \
		../glm/ext/matrix_float3x3_precision.hpp \
		../glm/mat3x4.hpp \
		../glm/ext/matrix_double3x4.hpp \
		../glm/detail/type_mat3x4.hpp \
		../glm/detail/type_mat3x4.inl \
		../glm/ext/matrix_double3x4_precision.hpp \
		../glm/ext/matrix_float3x4.hpp \
		../glm/ext/matrix_float3x4_precision.hpp \
		../glm/mat4x2.hpp \
		../glm/ext/matrix_double4x2.hpp \
		../glm/detail/type_mat4x2.hpp \
		../glm/detail/type_mat4x2.inl \
		../glm/ext/matrix_double4x2_precision.hpp \
		../glm/ext/matrix_float4x2.hpp \
		../glm/ext/matrix_float4x2_precision.hpp \
		../glm/mat4x3.hpp \
		../glm/ext/matrix_double4x3.hpp \
		../glm/detail/type_mat4x3.hpp \
		../glm/detail/type_mat4x3.inl \
		../glm/ext/matrix_double4x3_precision.hpp \
		../glm/ext/matrix_float4x3.hpp \
		../glm/ext/matrix_float4x3_precision.hpp \
		../glm/mat4x4.hpp \
		../glm/ext/matrix_double4x4.hpp \
		../glm/detail/type_mat4x4.hpp \
		../glm/detail/type_mat4x4.inl \
		../glm/detail/type_mat4x4_simd.inl \
		../glm/ext/matrix_double4x4_precision.hpp \
		../glm/ext/matrix_float4x4.hpp \
		../glm/ext/matrix_float4x4_precision.hpp \
		../glm/detail/func_matrix.inl \
		../glm/geometric.hpp \
		../glm/detail/func_geometric.inl \
		../glm/exponential.hpp \
		../glm/detail/type_vec1.hpp \
		../glm/detail/type_vec1.inl \
		../glm/detail/func_exponential.inl \
		../glm/vector_relational.hpp \
		../glm/detail/func_vector_relational.inl \
		../glm/detail/func_vector_relational_simd.inl \
		../glm/detail/_vectorize.hpp \
		../glm/detail/func_exponential_simd.inl \
		../glm/simd/exponential.h \
		../glm/common.hpp \
		../glm/detail/func_common.inl \
		../glm/detail/compute_common.hpp \
		../glm/detail/func_common_simd.inl \
		../glm/simd/common.h \
		../glm/detail/func_geometric_simd.inl \
		../glm/simd/geometric.h \
		../glm/detail/func_matrix_simd.inl \
		../glm/simd/matrix.h \
		../glm/ext/matrix_double2x2_precision.hpp \
		../glm/ext/matrix_float2x2.hpp \
		../glm/ext/matrix_float2x2_precision.hpp \
		../glm/trigonometric.hpp \
		../glm/detail/func_trigonometric.inl \
		../glm/detail/func_trigonometric_simd.inl \
		../glm/packing.hpp \
		../glm/detail/func_packing.inl \
		../glm/detail/type_half.hpp \
		../glm/detail/type_half.inl \
		../glm/detail/func_packing_simd.inl \
		../glm/integer.hpp \
		../glm/detail/func_integer.inl \
		../glm/detail/func_integer_simd.inl \
		../glm/simd/integer.h \
		../glm/gtc/matrix_transform.hpp \
		../glm/ext/matrix_projection.hpp \
		../glm/gtc/constants.hpp \
		../glm/ext/scalar_constants.hpp \
		../glm/ext/scalar_constants.inl \
		../glm/gtc/constants.inl \
		../glm/ext/matrix_projection.inl \
		../glm/ext/matrix_clip_space.hpp \
		../glm/ext/matrix_clip_space.inl \
		../glm/ext/matrix_transform.hpp \
		../glm/gtc/matrix_transform.inl \
		PointMass.h \
		../glm/gtc/type_ptr.hpp \
		../glm/gtc/quaternion.hpp \
		../glm/ext/vector_relational.hpp \
		../glm/ext/vector_relational.inl \
		../glm/detail/type_float.hpp \
		../glm/ext/quaternion_common.hpp \
		../glm/ext/quaternion_geometric.hpp \
		../glm/ext/quaternion_geometric.inl \
		../glm/ext/quaternion_common.inl \
		../glm/ext/quaternion_common_simd.inl \
		../glm/ext/quaternion_float.hpp \
		../glm/detail/type_quat.hpp \
		../glm/ext/quaternion_relational.hpp \
		../glm/ext/quaternion_relational.inl \
		../glm/detail/type_quat.inl \
		../glm/detail/type_quat_simd.inl \
		../glm/ext/quaternion_float_precision.hpp \
		../glm/ext/quaternion_double.hpp \
		../glm/ext/quaternion_double_precision.hpp \
		../glm/ext/quaternion_trigonometric.hpp \
		../glm/ext/quaternion_trigonometric.inl \
		../glm/ext/quaternion_transform.hpp \
		../glm/ext/quaternion_transform.inl \
		../glm/gtc/quaternion.inl \
		../glm/gtc/epsilon.hpp \
		../glm/gtc/epsilon.inl \
		../glm/gtc/quaternion_simd.inl \
		../glm/gtc/vec1.hpp \
		../glm/ext/vector_bool1.hpp \
		../glm/ext/vector_bool1_precision.hpp \
		../glm/ext/vector_float1.hpp \
		../glm/ext/vector_float1_precision.hpp \
		../glm/ext/vector_double1.hpp \
		../glm/ext/vector_double1_precision.hpp \
		../glm/ext/vector_int1.hpp \
		../glm/ext/vector_int1_precision.hpp \
		../glm/ext/vector_uint1.hpp \
		../glm/ext/vector_uint1_precision.hpp \
		../glm/gtc/type_ptr.inl \
		Spring.h \
		Wind.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Cloth.o Cloth.cpp

GObject.o: GObject.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GObject.o GObject.cpp

main.o: main.cpp RenderWidget.h \
		MousePick.h \
		Cartesian3.h \
		camera.h \
		../glm/glm.hpp \
		../glm/detail/_fixes.hpp \
		../glm/detail/setup.hpp \
		../glm/simd/platform.h \
		../glm/simd/neon.h \
		../glm/fwd.hpp \
		../glm/detail/qualifier.hpp \
		../glm/vec2.hpp \
		../glm/ext/vector_bool2.hpp \
		../glm/detail/type_vec2.hpp \
		../glm/detail/_swizzle.hpp \
		../glm/detail/_swizzle_func.hpp \
		../glm/detail/type_vec2.inl \
		../glm/detail/compute_vector_relational.hpp \
		../glm/ext/vector_bool2_precision.hpp \
		../glm/ext/vector_float2.hpp \
		../glm/ext/vector_float2_precision.hpp \
		../glm/ext/vector_double2.hpp \
		../glm/ext/vector_double2_precision.hpp \
		../glm/ext/vector_int2.hpp \
		../glm/ext/vector_int2_precision.hpp \
		../glm/ext/vector_uint2.hpp \
		../glm/ext/vector_uint2_precision.hpp \
		../glm/vec3.hpp \
		../glm/ext/vector_bool3.hpp \
		../glm/detail/type_vec3.hpp \
		../glm/detail/type_vec3.inl \
		../glm/ext/vector_bool3_precision.hpp \
		../glm/ext/vector_float3.hpp \
		../glm/ext/vector_float3_precision.hpp \
		../glm/ext/vector_double3.hpp \
		../glm/ext/vector_double3_precision.hpp \
		../glm/ext/vector_int3.hpp \
		../glm/ext/vector_int3_precision.hpp \
		../glm/ext/vector_uint3.hpp \
		../glm/ext/vector_uint3_precision.hpp \
		../glm/vec4.hpp \
		../glm/ext/vector_bool4.hpp \
		../glm/detail/type_vec4.hpp \
		../glm/detail/type_vec4.inl \
		../glm/detail/type_vec4_simd.inl \
		../glm/ext/vector_bool4_precision.hpp \
		../glm/ext/vector_float4.hpp \
		../glm/ext/vector_float4_precision.hpp \
		../glm/ext/vector_double4.hpp \
		../glm/ext/vector_double4_precision.hpp \
		../glm/ext/vector_int4.hpp \
		../glm/ext/vector_int4_precision.hpp \
		../glm/ext/vector_uint4.hpp \
		../glm/ext/vector_uint4_precision.hpp \
		../glm/mat2x2.hpp \
		../glm/ext/matrix_double2x2.hpp \
		../glm/detail/type_mat2x2.hpp \
		../glm/detail/type_mat2x2.inl \
		../glm/matrix.hpp \
		../glm/mat2x3.hpp \
		../glm/ext/matrix_double2x3.hpp \
		../glm/detail/type_mat2x3.hpp \
		../glm/detail/type_mat2x3.inl \
		../glm/ext/matrix_double2x3_precision.hpp \
		../glm/ext/matrix_float2x3.hpp \
		../glm/ext/matrix_float2x3_precision.hpp \
		../glm/mat2x4.hpp \
		../glm/ext/matrix_double2x4.hpp \
		../glm/detail/type_mat2x4.hpp \
		../glm/detail/type_mat2x4.inl \
		../glm/ext/matrix_double2x4_precision.hpp \
		../glm/ext/matrix_float2x4.hpp \
		../glm/ext/matrix_float2x4_precision.hpp \
		../glm/mat3x2.hpp \
		../glm/ext/matrix_double3x2.hpp \
		../glm/detail/type_mat3x2.hpp \
		../glm/detail/type_mat3x2.inl \
		../glm/ext/matrix_double3x2_precision.hpp \
		../glm/ext/matrix_float3x2.hpp \
		../glm/ext/matrix_float3x2_precision.hpp \
		../glm/mat3x3.hpp \
		../glm/ext/matrix_double3x3.hpp \
		../glm/detail/type_mat3x3.hpp \
		../glm/detail/type_mat3x3.inl \
		../glm/ext/matrix_double3x3_precision.hpp \
		../glm/ext/matrix_float3x3.hpp \
		../glm/ext/matrix_float3x3_precision.hpp \
		../glm/mat3x4.hpp \
		../glm/ext/matrix_double3x4.hpp \
		../glm/detail/type_mat3x4.hpp \
		../glm/detail/type_mat3x4.inl \
		../glm/ext/matrix_double3x4_precision.hpp \
		../glm/ext/matrix_float3x4.hpp \
		../glm/ext/matrix_float3x4_precision.hpp \
		../glm/mat4x2.hpp \
		../glm/ext/matrix_double4x2.hpp \
		../glm/detail/type_mat4x2.hpp \
		../glm/detail/type_mat4x2.inl \
		../glm/ext/matrix_double4x2_precision.hpp \
		../glm/ext/matrix_float4x2.hpp \
		../glm/ext/matrix_float4x2_precision.hpp \
		../glm/mat4x3.hpp \
		../glm/ext/matrix_double4x3.hpp \
		../glm/detail/type_mat4x3.hpp \
		../glm/detail/type_mat4x3.inl \
		../glm/ext/matrix_double4x3_precision.hpp \
		../glm/ext/matrix_float4x3.hpp \
		../glm/ext/matrix_float4x3_precision.hpp \
		../glm/mat4x4.hpp \
		../glm/ext/matrix_double4x4.hpp \
		../glm/detail/type_mat4x4.hpp \
		../glm/detail/type_mat4x4.inl \
		../glm/detail/type_mat4x4_simd.inl \
		../glm/ext/matrix_double4x4_precision.hpp \
		../glm/ext/matrix_float4x4.hpp \
		../glm/ext/matrix_float4x4_precision.hpp \
		../glm/detail/func_matrix.inl \
		../glm/geometric.hpp \
		../glm/detail/func_geometric.inl \
		../glm/exponential.hpp \
		../glm/detail/type_vec1.hpp \
		../glm/detail/type_vec1.inl \
		../glm/detail/func_exponential.inl \
		../glm/vector_relational.hpp \
		../glm/detail/func_vector_relational.inl \
		../glm/detail/func_vector_relational_simd.inl \
		../glm/detail/_vectorize.hpp \
		../glm/detail/func_exponential_simd.inl \
		../glm/simd/exponential.h \
		../glm/common.hpp \
		../glm/detail/func_common.inl \
		../glm/detail/compute_common.hpp \
		../glm/detail/func_common_simd.inl \
		../glm/simd/common.h \
		../glm/detail/func_geometric_simd.inl \
		../glm/simd/geometric.h \
		../glm/detail/func_matrix_simd.inl \
		../glm/simd/matrix.h \
		../glm/ext/matrix_double2x2_precision.hpp \
		../glm/ext/matrix_float2x2.hpp \
		../glm/ext/matrix_float2x2_precision.hpp \
		../glm/trigonometric.hpp \
		../glm/detail/func_trigonometric.inl \
		../glm/detail/func_trigonometric_simd.inl \
		../glm/packing.hpp \
		../glm/detail/func_packing.inl \
		../glm/detail/type_half.hpp \
		../glm/detail/type_half.inl \
		../glm/detail/func_packing_simd.inl \
		../glm/integer.hpp \
		../glm/detail/func_integer.inl \
		../glm/detail/func_integer_simd.inl \
		../glm/simd/integer.h \
		../glm/gtc/matrix_transform.hpp \
		../glm/ext/matrix_projection.hpp \
		../glm/gtc/constants.hpp \
		../glm/ext/scalar_constants.hpp \
		../glm/ext/scalar_constants.inl \
		../glm/gtc/constants.inl \
		../glm/ext/matrix_projection.inl \
		../glm/ext/matrix_clip_space.hpp \
		../glm/ext/matrix_clip_space.inl \
		../glm/ext/matrix_transform.hpp \
		../glm/gtc/matrix_transform.inl \
		../glm/gtc/type_ptr.hpp \
		../glm/gtc/quaternion.hpp \
		../glm/ext/vector_relational.hpp \
		../glm/ext/vector_relational.inl \
		../glm/detail/type_float.hpp \
		../glm/ext/quaternion_common.hpp \
		../glm/ext/quaternion_geometric.hpp \
		../glm/ext/quaternion_geometric.inl \
		../glm/ext/quaternion_common.inl \
		../glm/ext/quaternion_common_simd.inl \
		../glm/ext/quaternion_float.hpp \
		../glm/detail/type_quat.hpp \
		../glm/ext/quaternion_relational.hpp \
		../glm/ext/quaternion_relational.inl \
		../glm/detail/type_quat.inl \
		../glm/detail/type_quat_simd.inl \
		../glm/ext/quaternion_float_precision.hpp \
		../glm/ext/quaternion_double.hpp \
		../glm/ext/quaternion_double_precision.hpp \
		../glm/ext/quaternion_trigonometric.hpp \
		../glm/ext/quaternion_trigonometric.inl \
		../glm/ext/quaternion_transform.hpp \
		../glm/ext/quaternion_transform.inl \
		../glm/gtc/quaternion.inl \
		../glm/gtc/epsilon.hpp \
		../glm/gtc/epsilon.inl \
		../glm/gtc/quaternion_simd.inl \
		../glm/gtc/vec1.hpp \
		../glm/ext/vector_bool1.hpp \
		../glm/ext/vector_bool1_precision.hpp \
		../glm/ext/vector_float1.hpp \
		../glm/ext/vector_float1_precision.hpp \
		../glm/ext/vector_double1.hpp \
		../glm/ext/vector_double1_precision.hpp \
		../glm/ext/vector_int1.hpp \
		../glm/ext/vector_int1_precision.hpp \
		../glm/ext/vector_uint1.hpp \
		../glm/ext/vector_uint1_precision.hpp \
		../glm/gtc/type_ptr.inl \
		../glm/gtx/intersect.hpp \
		../glm/gtx/closest_point.hpp \
		../glm/gtx/closest_point.inl \
		../glm/gtx/vector_query.hpp \
		../glm/gtx/vector_query.inl \
		../glm/gtx/intersect.inl \
		MasterWidget.h \
		Simulation.h \
		Cloth.h \
		PointMass.h \
		Spring.h \
		Wind.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

MasterWidget.o: MasterWidget.cpp MasterWidget.h \
		RenderWidget.h \
		MousePick.h \
		Cartesian3.h \
		camera.h \
		../glm/glm.hpp \
		../glm/detail/_fixes.hpp \
		../glm/detail/setup.hpp \
		../glm/simd/platform.h \
		../glm/simd/neon.h \
		../glm/fwd.hpp \
		../glm/detail/qualifier.hpp \
		../glm/vec2.hpp \
		../glm/ext/vector_bool2.hpp \
		../glm/detail/type_vec2.hpp \
		../glm/detail/_swizzle.hpp \
		../glm/detail/_swizzle_func.hpp \
		../glm/detail/type_vec2.inl \
		../glm/detail/compute_vector_relational.hpp \
		../glm/ext/vector_bool2_precision.hpp \
		../glm/ext/vector_float2.hpp \
		../glm/ext/vector_float2_precision.hpp \
		../glm/ext/vector_double2.hpp \
		../glm/ext/vector_double2_precision.hpp \
		../glm/ext/vector_int2.hpp \
		../glm/ext/vector_int2_precision.hpp \
		../glm/ext/vector_uint2.hpp \
		../glm/ext/vector_uint2_precision.hpp \
		../glm/vec3.hpp \
		../glm/ext/vector_bool3.hpp \
		../glm/detail/type_vec3.hpp \
		../glm/detail/type_vec3.inl \
		../glm/ext/vector_bool3_precision.hpp \
		../glm/ext/vector_float3.hpp \
		../glm/ext/vector_float3_precision.hpp \
		../glm/ext/vector_double3.hpp \
		../glm/ext/vector_double3_precision.hpp \
		../glm/ext/vector_int3.hpp \
		../glm/ext/vector_int3_precision.hpp \
		../glm/ext/vector_uint3.hpp \
		../glm/ext/vector_uint3_precision.hpp \
		../glm/vec4.hpp \
		../glm/ext/vector_bool4.hpp \
		../glm/detail/type_vec4.hpp \
		../glm/detail/type_vec4.inl \
		../glm/detail/type_vec4_simd.inl \
		../glm/ext/vector_bool4_precision.hpp \
		../glm/ext/vector_float4.hpp \
		../glm/ext/vector_float4_precision.hpp \
		../glm/ext/vector_double4.hpp \
		../glm/ext/vector_double4_precision.hpp \
		../glm/ext/vector_int4.hpp \
		../glm/ext/vector_int4_precision.hpp \
		../glm/ext/vector_uint4.hpp \
		../glm/ext/vector_uint4_precision.hpp \
		../glm/mat2x2.hpp \
		../glm/ext/matrix_double2x2.hpp \
		../glm/detail/type_mat2x2.hpp \
		../glm/detail/type_mat2x2.inl \
		../glm/matrix.hpp \
		../glm/mat2x3.hpp \
		../glm/ext/matrix_double2x3.hpp \
		../glm/detail/type_mat2x3.hpp \
		../glm/detail/type_mat2x3.inl \
		../glm/ext/matrix_double2x3_precision.hpp \
		../glm/ext/matrix_float2x3.hpp \
		../glm/ext/matrix_float2x3_precision.hpp \
		../glm/mat2x4.hpp \
		../glm/ext/matrix_double2x4.hpp \
		../glm/detail/type_mat2x4.hpp \
		../glm/detail/type_mat2x4.inl \
		../glm/ext/matrix_double2x4_precision.hpp \
		../glm/ext/matrix_float2x4.hpp \
		../glm/ext/matrix_float2x4_precision.hpp \
		../glm/mat3x2.hpp \
		../glm/ext/matrix_double3x2.hpp \
		../glm/detail/type_mat3x2.hpp \
		../glm/detail/type_mat3x2.inl \
		../glm/ext/matrix_double3x2_precision.hpp \
		../glm/ext/matrix_float3x2.hpp \
		../glm/ext/matrix_float3x2_precision.hpp \
		../glm/mat3x3.hpp \
		../glm/ext/matrix_double3x3.hpp \
		../glm/detail/type_mat3x3.hpp \
		../glm/detail/type_mat3x3.inl \
		../glm/ext/matrix_double3x3_precision.hpp \
		../glm/ext/matrix_float3x3.hpp \
		../glm/ext/matrix_float3x3_precision.hpp \
		../glm/mat3x4.hpp \
		../glm/ext/matrix_double3x4.hpp \
		../glm/detail/type_mat3x4.hpp \
		../glm/detail/type_mat3x4.inl \
		../glm/ext/matrix_double3x4_precision.hpp \
		../glm/ext/matrix_float3x4.hpp \
		../glm/ext/matrix_float3x4_precision.hpp \
		../glm/mat4x2.hpp \
		../glm/ext/matrix_double4x2.hpp \
		../glm/detail/type_mat4x2.hpp \
		../glm/detail/type_mat4x2.inl \
		../glm/ext/matrix_double4x2_precision.hpp \
		../glm/ext/matrix_float4x2.hpp \
		../glm/ext/matrix_float4x2_precision.hpp \
		../glm/mat4x3.hpp \
		../glm/ext/matrix_double4x3.hpp \
		../glm/detail/type_mat4x3.hpp \
		../glm/detail/type_mat4x3.inl \
		../glm/ext/matrix_double4x3_precision.hpp \
		../glm/ext/matrix_float4x3.hpp \
		../glm/ext/matrix_float4x3_precision.hpp \
		../glm/mat4x4.hpp \
		../glm/ext/matrix_double4x4.hpp \
		../glm/detail/type_mat4x4.hpp \
		../glm/detail/type_mat4x4.inl \
		../glm/detail/type_mat4x4_simd.inl \
		../glm/ext/matrix_double4x4_precision.hpp \
		../glm/ext/matrix_float4x4.hpp \
		../glm/ext/matrix_float4x4_precision.hpp \
		../glm/detail/func_matrix.inl \
		../glm/geometric.hpp \
		../glm/detail/func_geometric.inl \
		../glm/exponential.hpp \
		../glm/detail/type_vec1.hpp \
		../glm/detail/type_vec1.inl \
		../glm/detail/func_exponential.inl \
		../glm/vector_relational.hpp \
		../glm/detail/func_vector_relational.inl \
		../glm/detail/func_vector_relational_simd.inl \
		../glm/detail/_vectorize.hpp \
		../glm/detail/func_exponential_simd.inl \
		../glm/simd/exponential.h \
		../glm/common.hpp \
		../glm/detail/func_common.inl \
		../glm/detail/compute_common.hpp \
		../glm/detail/func_common_simd.inl \
		../glm/simd/common.h \
		../glm/detail/func_geometric_simd.inl \
		../glm/simd/geometric.h \
		../glm/detail/func_matrix_simd.inl \
		../glm/simd/matrix.h \
		../glm/ext/matrix_double2x2_precision.hpp \
		../glm/ext/matrix_float2x2.hpp \
		../glm/ext/matrix_float2x2_precision.hpp \
		../glm/trigonometric.hpp \
		../glm/detail/func_trigonometric.inl \
		../glm/detail/func_trigonometric_simd.inl \
		../glm/packing.hpp \
		../glm/detail/func_packing.inl \
		../glm/detail/type_half.hpp \
		../glm/detail/type_half.inl \
		../glm/detail/func_packing_simd.inl \
		../glm/integer.hpp \
		../glm/detail/func_integer.inl \
		../glm/detail/func_integer_simd.inl \
		../glm/simd/integer.h \
		../glm/gtc/matrix_transform.hpp \
		../glm/ext/matrix_projection.hpp \
		../glm/gtc/constants.hpp \
		../glm/ext/scalar_constants.hpp \
		../glm/ext/scalar_constants.inl \
		../glm/gtc/constants.inl \
		../glm/ext/matrix_projection.inl \
		../glm/ext/matrix_clip_space.hpp \
		../glm/ext/matrix_clip_space.inl \
		../glm/ext/matrix_transform.hpp \
		../glm/gtc/matrix_transform.inl \
		../glm/gtc/type_ptr.hpp \
		../glm/gtc/quaternion.hpp \
		../glm/ext/vector_relational.hpp \
		../glm/ext/vector_relational.inl \
		../glm/detail/type_float.hpp \
		../glm/ext/quaternion_common.hpp \
		../glm/ext/quaternion_geometric.hpp \
		../glm/ext/quaternion_geometric.inl \
		../glm/ext/quaternion_common.inl \
		../glm/ext/quaternion_common_simd.inl \
		../glm/ext/quaternion_float.hpp \
		../glm/detail/type_quat.hpp \
		../glm/ext/quaternion_relational.hpp \
		../glm/ext/quaternion_relational.inl \
		../glm/detail/type_quat.inl \
		../glm/detail/type_quat_simd.inl \
		../glm/ext/quaternion_float_precision.hpp \
		../glm/ext/quaternion_double.hpp \
		../glm/ext/quaternion_double_precision.hpp \
		../glm/ext/quaternion_trigonometric.hpp \
		../glm/ext/quaternion_trigonometric.inl \
		../glm/ext/quaternion_transform.hpp \
		../glm/ext/quaternion_transform.inl \
		../glm/gtc/quaternion.inl \
		../glm/gtc/epsilon.hpp \
		../glm/gtc/epsilon.inl \
		../glm/gtc/quaternion_simd.inl \
		../glm/gtc/vec1.hpp \
		../glm/ext/vector_bool1.hpp \
		../glm/ext/vector_bool1_precision.hpp \
		../glm/ext/vector_float1.hpp \
		../glm/ext/vector_float1_precision.hpp \
		../glm/ext/vector_double1.hpp \
		../glm/ext/vector_double1_precision.hpp \
		../glm/ext/vector_int1.hpp \
		../glm/ext/vector_int1_precision.hpp \
		../glm/ext/vector_uint1.hpp \
		../glm/ext/vector_uint1_precision.hpp \
		../glm/gtc/type_ptr.inl \
		../glm/gtx/intersect.hpp \
		../glm/gtx/closest_point.hpp \
		../glm/gtx/closest_point.inl \
		../glm/gtx/vector_query.hpp \
		../glm/gtx/vector_query.inl \
		../glm/gtx/intersect.inl \
		Simulation.h \
		Cloth.h \
		PointMass.h \
		Spring.h \
		Wind.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MasterWidget.o MasterWidget.cpp

MousePick.o: MousePick.cpp MousePick.h \
		Cartesian3.h \
		camera.h \
		../glm/glm.hpp \
		../glm/detail/_fixes.hpp \
		../glm/detail/setup.hpp \
		../glm/simd/platform.h \
		../glm/simd/neon.h \
		../glm/fwd.hpp \
		../glm/detail/qualifier.hpp \
		../glm/vec2.hpp \
		../glm/ext/vector_bool2.hpp \
		../glm/detail/type_vec2.hpp \
		../glm/detail/_swizzle.hpp \
		../glm/detail/_swizzle_func.hpp \
		../glm/detail/type_vec2.inl \
		../glm/detail/compute_vector_relational.hpp \
		../glm/ext/vector_bool2_precision.hpp \
		../glm/ext/vector_float2.hpp \
		../glm/ext/vector_float2_precision.hpp \
		../glm/ext/vector_double2.hpp \
		../glm/ext/vector_double2_precision.hpp \
		../glm/ext/vector_int2.hpp \
		../glm/ext/vector_int2_precision.hpp \
		../glm/ext/vector_uint2.hpp \
		../glm/ext/vector_uint2_precision.hpp \
		../glm/vec3.hpp \
		../glm/ext/vector_bool3.hpp \
		../glm/detail/type_vec3.hpp \
		../glm/detail/type_vec3.inl \
		../glm/ext/vector_bool3_precision.hpp \
		../glm/ext/vector_float3.hpp \
		../glm/ext/vector_float3_precision.hpp \
		../glm/ext/vector_double3.hpp \
		../glm/ext/vector_double3_precision.hpp \
		../glm/ext/vector_int3.hpp \
		../glm/ext/vector_int3_precision.hpp \
		../glm/ext/vector_uint3.hpp \
		../glm/ext/vector_uint3_precision.hpp \
		../glm/vec4.hpp \
		../glm/ext/vector_bool4.hpp \
		../glm/detail/type_vec4.hpp \
		../glm/detail/type_vec4.inl \
		../glm/detail/type_vec4_simd.inl \
		../glm/ext/vector_bool4_precision.hpp \
		../glm/ext/vector_float4.hpp \
		../glm/ext/vector_float4_precision.hpp \
		../glm/ext/vector_double4.hpp \
		../glm/ext/vector_double4_precision.hpp \
		../glm/ext/vector_int4.hpp \
		../glm/ext/vector_int4_precision.hpp \
		../glm/ext/vector_uint4.hpp \
		../glm/ext/vector_uint4_precision.hpp \
		../glm/mat2x2.hpp \
		../glm/ext/matrix_double2x2.hpp \
		../glm/detail/type_mat2x2.hpp \
		../glm/detail/type_mat2x2.inl \
		../glm/matrix.hpp \
		../glm/mat2x3.hpp \
		../glm/ext/matrix_double2x3.hpp \
		../glm/detail/type_mat2x3.hpp \
		../glm/detail/type_mat2x3.inl \
		../glm/ext/matrix_double2x3_precision.hpp \
		../glm/ext/matrix_float2x3.hpp \
		../glm/ext/matrix_float2x3_precision.hpp \
		../glm/mat2x4.hpp \
		../glm/ext/matrix_double2x4.hpp \
		../glm/detail/type_mat2x4.hpp \
		../glm/detail/type_mat2x4.inl \
		../glm/ext/matrix_double2x4_precision.hpp \
		../glm/ext/matrix_float2x4.hpp \
		../glm/ext/matrix_float2x4_precision.hpp \
		../glm/mat3x2.hpp \
		../glm/ext/matrix_double3x2.hpp \
		../glm/detail/type_mat3x2.hpp \
		../glm/detail/type_mat3x2.inl \
		../glm/ext/matrix_double3x2_precision.hpp \
		../glm/ext/matrix_float3x2.hpp \
		../glm/ext/matrix_float3x2_precision.hpp \
		../glm/mat3x3.hpp \
		../glm/ext/matrix_double3x3.hpp \
		../glm/detail/type_mat3x3.hpp \
		../glm/detail/type_mat3x3.inl \
		../glm/ext/matrix_double3x3_precision.hpp \
		../glm/ext/matrix_float3x3.hpp \
		../glm/ext/matrix_float3x3_precision.hpp \
		../glm/mat3x4.hpp \
		../glm/ext/matrix_double3x4.hpp \
		../glm/detail/type_mat3x4.hpp \
		../glm/detail/type_mat3x4.inl \
		../glm/ext/matrix_double3x4_precision.hpp \
		../glm/ext/matrix_float3x4.hpp \
		../glm/ext/matrix_float3x4_precision.hpp \
		../glm/mat4x2.hpp \
		../glm/ext/matrix_double4x2.hpp \
		../glm/detail/type_mat4x2.hpp \
		../glm/detail/type_mat4x2.inl \
		../glm/ext/matrix_double4x2_precision.hpp \
		../glm/ext/matrix_float4x2.hpp \
		../glm/ext/matrix_float4x2_precision.hpp \
		../glm/mat4x3.hpp \
		../glm/ext/matrix_double4x3.hpp \
		../glm/detail/type_mat4x3.hpp \
		../glm/detail/type_mat4x3.inl \
		../glm/ext/matrix_double4x3_precision.hpp \
		../glm/ext/matrix_float4x3.hpp \
		../glm/ext/matrix_float4x3_precision.hpp \
		../glm/mat4x4.hpp \
		../glm/ext/matrix_double4x4.hpp \
		../glm/detail/type_mat4x4.hpp \
		../glm/detail/type_mat4x4.inl \
		../glm/detail/type_mat4x4_simd.inl \
		../glm/ext/matrix_double4x4_precision.hpp \
		../glm/ext/matrix_float4x4.hpp \
		../glm/ext/matrix_float4x4_precision.hpp \
		../glm/detail/func_matrix.inl \
		../glm/geometric.hpp \
		../glm/detail/func_geometric.inl \
		../glm/exponential.hpp \
		../glm/detail/type_vec1.hpp \
		../glm/detail/type_vec1.inl \
		../glm/detail/func_exponential.inl \
		../glm/vector_relational.hpp \
		../glm/detail/func_vector_relational.inl \
		../glm/detail/func_vector_relational_simd.inl \
		../glm/detail/_vectorize.hpp \
		../glm/detail/func_exponential_simd.inl \
		../glm/simd/exponential.h \
		../glm/common.hpp \
		../glm/detail/func_common.inl \
		../glm/detail/compute_common.hpp \
		../glm/detail/func_common_simd.inl \
		../glm/simd/common.h \
		../glm/detail/func_geometric_simd.inl \
		../glm/simd/geometric.h \
		../glm/detail/func_matrix_simd.inl \
		../glm/simd/matrix.h \
		../glm/ext/matrix_double2x2_precision.hpp \
		../glm/ext/matrix_float2x2.hpp \
		../glm/ext/matrix_float2x2_precision.hpp \
		../glm/trigonometric.hpp \
		../glm/detail/func_trigonometric.inl \
		../glm/detail/func_trigonometric_simd.inl \
		../glm/packing.hpp \
		../glm/detail/func_packing.inl \
		../glm/detail/type_half.hpp \
		../glm/detail/type_half.inl \
		../glm/detail/func_packing_simd.inl \
		../glm/integer.hpp \
		../glm/detail/func_integer.inl \
		../glm/detail/func_integer_simd.inl \
		../glm/simd/integer.h \
		../glm/gtc/matrix_transform.hpp \
		../glm/ext/matrix_projection.hpp \
		../glm/gtc/constants.hpp \
		../glm/ext/scalar_constants.hpp \
		../glm/ext/scalar_constants.inl \
		../glm/gtc/constants.inl \
		../glm/ext/matrix_projection.inl \
		../glm/ext/matrix_clip_space.hpp \
		../glm/ext/matrix_clip_space.inl \
		../glm/ext/matrix_transform.hpp \
		../glm/gtc/matrix_transform.inl \
		../glm/gtc/type_ptr.hpp \
		../glm/gtc/quaternion.hpp \
		../glm/ext/vector_relational.hpp \
		../glm/ext/vector_relational.inl \
		../glm/detail/type_float.hpp \
		../glm/ext/quaternion_common.hpp \
		../glm/ext/quaternion_geometric.hpp \
		../glm/ext/quaternion_geometric.inl \
		../glm/ext/quaternion_common.inl \
		../glm/ext/quaternion_common_simd.inl \
		../glm/ext/quaternion_float.hpp \
		../glm/detail/type_quat.hpp \
		../glm/ext/quaternion_relational.hpp \
		../glm/ext/quaternion_relational.inl \
		../glm/detail/type_quat.inl \
		../glm/detail/type_quat_simd.inl \
		../glm/ext/quaternion_float_precision.hpp \
		../glm/ext/quaternion_double.hpp \
		../glm/ext/quaternion_double_precision.hpp \
		../glm/ext/quaternion_trigonometric.hpp \
		../glm/ext/quaternion_trigonometric.inl \
		../glm/ext/quaternion_transform.hpp \
		../glm/ext/quaternion_transform.inl \
		../glm/gtc/quaternion.inl \
		../glm/gtc/epsilon.hpp \
		../glm/gtc/epsilon.inl \
		../glm/gtc/quaternion_simd.inl \
		../glm/gtc/vec1.hpp \
		../glm/ext/vector_bool1.hpp \
		../glm/ext/vector_bool1_precision.hpp \
		../glm/ext/vector_float1.hpp \
		../glm/ext/vector_float1_precision.hpp \
		../glm/ext/vector_double1.hpp \
		../glm/ext/vector_double1_precision.hpp \
		../glm/ext/vector_int1.hpp \
		../glm/ext/vector_int1_precision.hpp \
		../glm/ext/vector_uint1.hpp \
		../glm/ext/vector_uint1_precision.hpp \
		../glm/gtc/type_ptr.inl \
		../glm/gtx/intersect.hpp \
		../glm/gtx/closest_point.hpp \
		../glm/gtx/closest_point.inl \
		../glm/gtx/vector_query.hpp \
		../glm/gtx/vector_query.inl \
		../glm/gtx/intersect.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MousePick.o MousePick.cpp

PointMass.o: PointMass.cpp PointMass.h \
		Cartesian3.h \
		camera.h \
		../glm/glm.hpp \
		../glm/detail/_fixes.hpp \
		../glm/detail/setup.hpp \
		../glm/simd/platform.h \
		../glm/simd/neon.h \
		../glm/fwd.hpp \
		../glm/detail/qualifier.hpp \
		../glm/vec2.hpp \
		../glm/ext/vector_bool2.hpp \
		../glm/detail/type_vec2.hpp \
		../glm/detail/_swizzle.hpp \
		../glm/detail/_swizzle_func.hpp \
		../glm/detail/type_vec2.inl \
		../glm/detail/compute_vector_relational.hpp \
		../glm/ext/vector_bool2_precision.hpp \
		../glm/ext/vector_float2.hpp \
		../glm/ext/vector_float2_precision.hpp \
		../glm/ext/vector_double2.hpp \
		../glm/ext/vector_double2_precision.hpp \
		../glm/ext/vector_int2.hpp \
		../glm/ext/vector_int2_precision.hpp \
		../glm/ext/vector_uint2.hpp \
		../glm/ext/vector_uint2_precision.hpp \
		../glm/vec3.hpp \
		../glm/ext/vector_bool3.hpp \
		../glm/detail/type_vec3.hpp \
		../glm/detail/type_vec3.inl \
		../glm/ext/vector_bool3_precision.hpp \
		../glm/ext/vector_float3.hpp \
		../glm/ext/vector_float3_precision.hpp \
		../glm/ext/vector_double3.hpp \
		../glm/ext/vector_double3_precision.hpp \
		../glm/ext/vector_int3.hpp \
		../glm/ext/vector_int3_precision.hpp \
		../glm/ext/vector_uint3.hpp \
		../glm/ext/vector_uint3_precision.hpp \
		../glm/vec4.hpp \
		../glm/ext/vector_bool4.hpp \
		../glm/detail/type_vec4.hpp \
		../glm/detail/type_vec4.inl \
		../glm/detail/type_vec4_simd.inl \
		../glm/ext/vector_bool4_precision.hpp \
		../glm/ext/vector_float4.hpp \
		../glm/ext/vector_float4_precision.hpp \
		../glm/ext/vector_double4.hpp \
		../glm/ext/vector_double4_precision.hpp \
		../glm/ext/vector_int4.hpp \
		../glm/ext/vector_int4_precision.hpp \
		../glm/ext/vector_uint4.hpp \
		../glm/ext/vector_uint4_precision.hpp \
		../glm/mat2x2.hpp \
		../glm/ext/matrix_double2x2.hpp \
		../glm/detail/type_mat2x2.hpp \
		../glm/detail/type_mat2x2.inl \
		../glm/matrix.hpp \
		../glm/mat2x3.hpp \
		../glm/ext/matrix_double2x3.hpp \
		../glm/detail/type_mat2x3.hpp \
		../glm/detail/type_mat2x3.inl \
		../glm/ext/matrix_double2x3_precision.hpp \
		../glm/ext/matrix_float2x3.hpp \
		../glm/ext/matrix_float2x3_precision.hpp \
		../glm/mat2x4.hpp \
		../glm/ext/matrix_double2x4.hpp \
		../glm/detail/type_mat2x4.hpp \
		../glm/detail/type_mat2x4.inl \
		../glm/ext/matrix_double2x4_precision.hpp \
		../glm/ext/matrix_float2x4.hpp \
		../glm/ext/matrix_float2x4_precision.hpp \
		../glm/mat3x2.hpp \
		../glm/ext/matrix_double3x2.hpp \
		../glm/detail/type_mat3x2.hpp \
		../glm/detail/type_mat3x2.inl \
		../glm/ext/matrix_double3x2_precision.hpp \
		../glm/ext/matrix_float3x2.hpp \
		../glm/ext/matrix_float3x2_precision.hpp \
		../glm/mat3x3.hpp \
		../glm/ext/matrix_double3x3.hpp \
		../glm/detail/type_mat3x3.hpp \
		../glm/detail/type_mat3x3.inl \
		../glm/ext/matrix_double3x3_precision.hpp \
		../glm/ext/matrix_float3x3.hpp \
		../glm/ext/matrix_float3x3_precision.hpp \
		../glm/mat3x4.hpp \
		../glm/ext/matrix_double3x4.hpp \
		../glm/detail/type_mat3x4.hpp \
		../glm/detail/type_mat3x4.inl \
		../glm/ext/matrix_double3x4_precision.hpp \
		../glm/ext/matrix_float3x4.hpp \
		../glm/ext/matrix_float3x4_precision.hpp \
		../glm/mat4x2.hpp \
		../glm/ext/matrix_double4x2.hpp \
		../glm/detail/type_mat4x2.hpp \
		../glm/detail/type_mat4x2.inl \
		../glm/ext/matrix_double4x2_precision.hpp \
		../glm/ext/matrix_float4x2.hpp \
		../glm/ext/matrix_float4x2_precision.hpp \
		../glm/mat4x3.hpp \
		../glm/ext/matrix_double4x3.hpp \
		../glm/detail/type_mat4x3.hpp \
		../glm/detail/type_mat4x3.inl \
		../glm/ext/matrix_double4x3_precision.hpp \
		../glm/ext/matrix_float4x3.hpp \
		../glm/ext/matrix_float4x3_precision.hpp \
		../glm/mat4x4.hpp \
		../glm/ext/matrix_double4x4.hpp \
		../glm/detail/type_mat4x4.hpp \
		../glm/detail/type_mat4x4.inl \
		../glm/detail/type_mat4x4_simd.inl \
		../glm/ext/matrix_double4x4_precision.hpp \
		../glm/ext/matrix_float4x4.hpp \
		../glm/ext/matrix_float4x4_precision.hpp \
		../glm/detail/func_matrix.inl \
		../glm/geometric.hpp \
		../glm/detail/func_geometric.inl \
		../glm/exponential.hpp \
		../glm/detail/type_vec1.hpp \
		../glm/detail/type_vec1.inl \
		../glm/detail/func_exponential.inl \
		../glm/vector_relational.hpp \
		../glm/detail/func_vector_relational.inl \
		../glm/detail/func_vector_relational_simd.inl \
		../glm/detail/_vectorize.hpp \
		../glm/detail/func_exponential_simd.inl \
		../glm/simd/exponential.h \
		../glm/common.hpp \
		../glm/detail/func_common.inl \
		../glm/detail/compute_common.hpp \
		../glm/detail/func_common_simd.inl \
		../glm/simd/common.h \
		../glm/detail/func_geometric_simd.inl \
		../glm/simd/geometric.h \
		../glm/detail/func_matrix_simd.inl \
		../glm/simd/matrix.h \
		../glm/ext/matrix_double2x2_precision.hpp \
		../glm/ext/matrix_float2x2.hpp \
		../glm/ext/matrix_float2x2_precision.hpp \
		../glm/trigonometric.hpp \
		../glm/detail/func_trigonometric.inl \
		../glm/detail/func_trigonometric_simd.inl \
		../glm/packing.hpp \
		../glm/detail/func_packing.inl \
		../glm/detail/type_half.hpp \
		../glm/detail/type_half.inl \
		../glm/detail/func_packing_simd.inl \
		../glm/integer.hpp \
		../glm/detail/func_integer.inl \
		../glm/detail/func_integer_simd.inl \
		../glm/simd/integer.h \
		../glm/gtc/matrix_transform.hpp \
		../glm/ext/matrix_projection.hpp \
		../glm/gtc/constants.hpp \
		../glm/ext/scalar_constants.hpp \
		../glm/ext/scalar_constants.inl \
		../glm/gtc/constants.inl \
		../glm/ext/matrix_projection.inl \
		../glm/ext/matrix_clip_space.hpp \
		../glm/ext/matrix_clip_space.inl \
		../glm/ext/matrix_transform.hpp \
		../glm/gtc/matrix_transform.inl \
		../glm/gtc/type_ptr.hpp \
		../glm/gtc/quaternion.hpp \
		../glm/ext/vector_relational.hpp \
		../glm/ext/vector_relational.inl \
		../glm/detail/type_float.hpp \
		../glm/ext/quaternion_common.hpp \
		../glm/ext/quaternion_geometric.hpp \
		../glm/ext/quaternion_geometric.inl \
		../glm/ext/quaternion_common.inl \
		../glm/ext/quaternion_common_simd.inl \
		../glm/ext/quaternion_float.hpp \
		../glm/detail/type_quat.hpp \
		../glm/ext/quaternion_relational.hpp \
		../glm/ext/quaternion_relational.inl \
		../glm/detail/type_quat.inl \
		../glm/detail/type_quat_simd.inl \
		../glm/ext/quaternion_float_precision.hpp \
		../glm/ext/quaternion_double.hpp \
		../glm/ext/quaternion_double_precision.hpp \
		../glm/ext/quaternion_trigonometric.hpp \
		../glm/ext/quaternion_trigonometric.inl \
		../glm/ext/quaternion_transform.hpp \
		../glm/ext/quaternion_transform.inl \
		../glm/gtc/quaternion.inl \
		../glm/gtc/epsilon.hpp \
		../glm/gtc/epsilon.inl \
		../glm/gtc/quaternion_simd.inl \
		../glm/gtc/vec1.hpp \
		../glm/ext/vector_bool1.hpp \
		../glm/ext/vector_bool1_precision.hpp \
		../glm/ext/vector_float1.hpp \
		../glm/ext/vector_float1_precision.hpp \
		../glm/ext/vector_double1.hpp \
		../glm/ext/vector_double1_precision.hpp \
		../glm/ext/vector_int1.hpp \
		../glm/ext/vector_int1_precision.hpp \
		../glm/ext/vector_uint1.hpp \
		../glm/ext/vector_uint1_precision.hpp \
		../glm/gtc/type_ptr.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PointMass.o PointMass.cpp

RenderWidget.o: RenderWidget.cpp RenderWidget.h \
		MousePick.h \
		Cartesian3.h \
		camera.h \
		../glm/glm.hpp \
		../glm/detail/_fixes.hpp \
		../glm/detail/setup.hpp \
		../glm/simd/platform.h \
		../glm/simd/neon.h \
		../glm/fwd.hpp \
		../glm/detail/qualifier.hpp \
		../glm/vec2.hpp \
		../glm/ext/vector_bool2.hpp \
		../glm/detail/type_vec2.hpp \
		../glm/detail/_swizzle.hpp \
		../glm/detail/_swizzle_func.hpp \
		../glm/detail/type_vec2.inl \
		../glm/detail/compute_vector_relational.hpp \
		../glm/ext/vector_bool2_precision.hpp \
		../glm/ext/vector_float2.hpp \
		../glm/ext/vector_float2_precision.hpp \
		../glm/ext/vector_double2.hpp \
		../glm/ext/vector_double2_precision.hpp \
		../glm/ext/vector_int2.hpp \
		../glm/ext/vector_int2_precision.hpp \
		../glm/ext/vector_uint2.hpp \
		../glm/ext/vector_uint2_precision.hpp \
		../glm/vec3.hpp \
		../glm/ext/vector_bool3.hpp \
		../glm/detail/type_vec3.hpp \
		../glm/detail/type_vec3.inl \
		../glm/ext/vector_bool3_precision.hpp \
		../glm/ext/vector_float3.hpp \
		../glm/ext/vector_float3_precision.hpp \
		../glm/ext/vector_double3.hpp \
		../glm/ext/vector_double3_precision.hpp \
		../glm/ext/vector_int3.hpp \
		../glm/ext/vector_int3_precision.hpp \
		../glm/ext/vector_uint3.hpp \
		../glm/ext/vector_uint3_precision.hpp \
		../glm/vec4.hpp \
		../glm/ext/vector_bool4.hpp \
		../glm/detail/type_vec4.hpp \
		../glm/detail/type_vec4.inl \
		../glm/detail/type_vec4_simd.inl \
		../glm/ext/vector_bool4_precision.hpp \
		../glm/ext/vector_float4.hpp \
		../glm/ext/vector_float4_precision.hpp \
		../glm/ext/vector_double4.hpp \
		../glm/ext/vector_double4_precision.hpp \
		../glm/ext/vector_int4.hpp \
		../glm/ext/vector_int4_precision.hpp \
		../glm/ext/vector_uint4.hpp \
		../glm/ext/vector_uint4_precision.hpp \
		../glm/mat2x2.hpp \
		../glm/ext/matrix_double2x2.hpp \
		../glm/detail/type_mat2x2.hpp \
		../glm/detail/type_mat2x2.inl \
		../glm/matrix.hpp \
		../glm/mat2x3.hpp \
		../glm/ext/matrix_double2x3.hpp \
		../glm/detail/type_mat2x3.hpp \
		../glm/detail/type_mat2x3.inl \
		../glm/ext/matrix_double2x3_precision.hpp \
		../glm/ext/matrix_float2x3.hpp \
		../glm/ext/matrix_float2x3_precision.hpp \
		../glm/mat2x4.hpp \
		../glm/ext/matrix_double2x4.hpp \
		../glm/detail/type_mat2x4.hpp \
		../glm/detail/type_mat2x4.inl \
		../glm/ext/matrix_double2x4_precision.hpp \
		../glm/ext/matrix_float2x4.hpp \
		../glm/ext/matrix_float2x4_precision.hpp \
		../glm/mat3x2.hpp \
		../glm/ext/matrix_double3x2.hpp \
		../glm/detail/type_mat3x2.hpp \
		../glm/detail/type_mat3x2.inl \
		../glm/ext/matrix_double3x2_precision.hpp \
		../glm/ext/matrix_float3x2.hpp \
		../glm/ext/matrix_float3x2_precision.hpp \
		../glm/mat3x3.hpp \
		../glm/ext/matrix_double3x3.hpp \
		../glm/detail/type_mat3x3.hpp \
		../glm/detail/type_mat3x3.inl \
		../glm/ext/matrix_double3x3_precision.hpp \
		../glm/ext/matrix_float3x3.hpp \
		../glm/ext/matrix_float3x3_precision.hpp \
		../glm/mat3x4.hpp \
		../glm/ext/matrix_double3x4.hpp \
		../glm/detail/type_mat3x4.hpp \
		../glm/detail/type_mat3x4.inl \
		../glm/ext/matrix_double3x4_precision.hpp \
		../glm/ext/matrix_float3x4.hpp \
		../glm/ext/matrix_float3x4_precision.hpp \
		../glm/mat4x2.hpp \
		../glm/ext/matrix_double4x2.hpp \
		../glm/detail/type_mat4x2.hpp \
		../glm/detail/type_mat4x2.inl \
		../glm/ext/matrix_double4x2_precision.hpp \
		../glm/ext/matrix_float4x2.hpp \
		../glm/ext/matrix_float4x2_precision.hpp \
		../glm/mat4x3.hpp \
		../glm/ext/matrix_double4x3.hpp \
		../glm/detail/type_mat4x3.hpp \
		../glm/detail/type_mat4x3.inl \
		../glm/ext/matrix_double4x3_precision.hpp \
		../glm/ext/matrix_float4x3.hpp \
		../glm/ext/matrix_float4x3_precision.hpp \
		../glm/mat4x4.hpp \
		../glm/ext/matrix_double4x4.hpp \
		../glm/detail/type_mat4x4.hpp \
		../glm/detail/type_mat4x4.inl \
		../glm/detail/type_mat4x4_simd.inl \
		../glm/ext/matrix_double4x4_precision.hpp \
		../glm/ext/matrix_float4x4.hpp \
		../glm/ext/matrix_float4x4_precision.hpp \
		../glm/detail/func_matrix.inl \
		../glm/geometric.hpp \
		../glm/detail/func_geometric.inl \
		../glm/exponential.hpp \
		../glm/detail/type_vec1.hpp \
		../glm/detail/type_vec1.inl \
		../glm/detail/func_exponential.inl \
		../glm/vector_relational.hpp \
		../glm/detail/func_vector_relational.inl \
		../glm/detail/func_vector_relational_simd.inl \
		../glm/detail/_vectorize.hpp \
		../glm/detail/func_exponential_simd.inl \
		../glm/simd/exponential.h \
		../glm/common.hpp \
		../glm/detail/func_common.inl \
		../glm/detail/compute_common.hpp \
		../glm/detail/func_common_simd.inl \
		../glm/simd/common.h \
		../glm/detail/func_geometric_simd.inl \
		../glm/simd/geometric.h \
		../glm/detail/func_matrix_simd.inl \
		../glm/simd/matrix.h \
		../glm/ext/matrix_double2x2_precision.hpp \
		../glm/ext/matrix_float2x2.hpp \
		../glm/ext/matrix_float2x2_precision.hpp \
		../glm/trigonometric.hpp \
		../glm/detail/func_trigonometric.inl \
		../glm/detail/func_trigonometric_simd.inl \
		../glm/packing.hpp \
		../glm/detail/func_packing.inl \
		../glm/detail/type_half.hpp \
		../glm/detail/type_half.inl \
		../glm/detail/func_packing_simd.inl \
		../glm/integer.hpp \
		../glm/detail/func_integer.inl \
		../glm/detail/func_integer_simd.inl \
		../glm/simd/integer.h \
		../glm/gtc/matrix_transform.hpp \
		../glm/ext/matrix_projection.hpp \
		../glm/gtc/constants.hpp \
		../glm/ext/scalar_constants.hpp \
		../glm/ext/scalar_constants.inl \
		../glm/gtc/constants.inl \
		../glm/ext/matrix_projection.inl \
		../glm/ext/matrix_clip_space.hpp \
		../glm/ext/matrix_clip_space.inl \
		../glm/ext/matrix_transform.hpp \
		../glm/gtc/matrix_transform.inl \
		../glm/gtc/type_ptr.hpp \
		../glm/gtc/quaternion.hpp \
		../glm/ext/vector_relational.hpp \
		../glm/ext/vector_relational.inl \
		../glm/detail/type_float.hpp \
		../glm/ext/quaternion_common.hpp \
		../glm/ext/quaternion_geometric.hpp \
		../glm/ext/quaternion_geometric.inl \
		../glm/ext/quaternion_common.inl \
		../glm/ext/quaternion_common_simd.inl \
		../glm/ext/quaternion_float.hpp \
		../glm/detail/type_quat.hpp \
		../glm/ext/quaternion_relational.hpp \
		../glm/ext/quaternion_relational.inl \
		../glm/detail/type_quat.inl \
		../glm/detail/type_quat_simd.inl \
		../glm/ext/quaternion_float_precision.hpp \
		../glm/ext/quaternion_double.hpp \
		../glm/ext/quaternion_double_precision.hpp \
		../glm/ext/quaternion_trigonometric.hpp \
		../glm/ext/quaternion_trigonometric.inl \
		../glm/ext/quaternion_transform.hpp \
		../glm/ext/quaternion_transform.inl \
		../glm/gtc/quaternion.inl \
		../glm/gtc/epsilon.hpp \
		../glm/gtc/epsilon.inl \
		../glm/gtc/quaternion_simd.inl \
		../glm/gtc/vec1.hpp \
		../glm/ext/vector_bool1.hpp \
		../glm/ext/vector_bool1_precision.hpp \
		../glm/ext/vector_float1.hpp \
		../glm/ext/vector_float1_precision.hpp \
		../glm/ext/vector_double1.hpp \
		../glm/ext/vector_double1_precision.hpp \
		../glm/ext/vector_int1.hpp \
		../glm/ext/vector_int1_precision.hpp \
		../glm/ext/vector_uint1.hpp \
		../glm/ext/vector_uint1_precision.hpp \
		../glm/gtc/type_ptr.inl \
		../glm/gtx/intersect.hpp \
		../glm/gtx/closest_point.hpp \
		../glm/gtx/closest_point.inl \
		../glm/gtx/vector_query.hpp \
		../glm/gtx/vector_query.inl \
		../glm/gtx/intersect.inl \
		MasterWidget.h \
		Simulation.h \
		Cloth.h \
		PointMass.h \
		Spring.h \
		Wind.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RenderWidget.o RenderWidget.cpp

Simulation.o: Simulation.cpp Simulation.h \
		Cartesian3.h \
		camera.h \
		../glm/glm.hpp \
		../glm/detail/_fixes.hpp \
		../glm/detail/setup.hpp \
		../glm/simd/platform.h \
		../glm/simd/neon.h \
		../glm/fwd.hpp \
		../glm/detail/qualifier.hpp \
		../glm/vec2.hpp \
		../glm/ext/vector_bool2.hpp \
		../glm/detail/type_vec2.hpp \
		../glm/detail/_swizzle.hpp \
		../glm/detail/_swizzle_func.hpp \
		../glm/detail/type_vec2.inl \
		../glm/detail/compute_vector_relational.hpp \
		../glm/ext/vector_bool2_precision.hpp \
		../glm/ext/vector_float2.hpp \
		../glm/ext/vector_float2_precision.hpp \
		../glm/ext/vector_double2.hpp \
		../glm/ext/vector_double2_precision.hpp \
		../glm/ext/vector_int2.hpp \
		../glm/ext/vector_int2_precision.hpp \
		../glm/ext/vector_uint2.hpp \
		../glm/ext/vector_uint2_precision.hpp \
		../glm/vec3.hpp \
		../glm/ext/vector_bool3.hpp \
		../glm/detail/type_vec3.hpp \
		../glm/detail/type_vec3.inl \
		../glm/ext/vector_bool3_precision.hpp \
		../glm/ext/vector_float3.hpp \
		../glm/ext/vector_float3_precision.hpp \
		../glm/ext/vector_double3.hpp \
		../glm/ext/vector_double3_precision.hpp \
		../glm/ext/vector_int3.hpp \
		../glm/ext/vector_int3_precision.hpp \
		../glm/ext/vector_uint3.hpp \
		../glm/ext/vector_uint3_precision.hpp \
		../glm/vec4.hpp \
		../glm/ext/vector_bool4.hpp \
		../glm/detail/type_vec4.hpp \
		../glm/detail/type_vec4.inl \
		../glm/detail/type_vec4_simd.inl \
		../glm/ext/vector_bool4_precision.hpp \
		../glm/ext/vector_float4.hpp \
		../glm/ext/vector_float4_precision.hpp \
		../glm/ext/vector_double4.hpp \
		../glm/ext/vector_double4_precision.hpp \
		../glm/ext/vector_int4.hpp \
		../glm/ext/vector_int4_precision.hpp \
		../glm/ext/vector_uint4.hpp \
		../glm/ext/vector_uint4_precision.hpp \
		../glm/mat2x2.hpp \
		../glm/ext/matrix_double2x2.hpp \
		../glm/detail/type_mat2x2.hpp \
		../glm/detail/type_mat2x2.inl \
		../glm/matrix.hpp \
		../glm/mat2x3.hpp \
		../glm/ext/matrix_double2x3.hpp \
		../glm/detail/type_mat2x3.hpp \
		../glm/detail/type_mat2x3.inl \
		../glm/ext/matrix_double2x3_precision.hpp \
		../glm/ext/matrix_float2x3.hpp \
		../glm/ext/matrix_float2x3_precision.hpp \
		../glm/mat2x4.hpp \
		../glm/ext/matrix_double2x4.hpp \
		../glm/detail/type_mat2x4.hpp \
		../glm/detail/type_mat2x4.inl \
		../glm/ext/matrix_double2x4_precision.hpp \
		../glm/ext/matrix_float2x4.hpp \
		../glm/ext/matrix_float2x4_precision.hpp \
		../glm/mat3x2.hpp \
		../glm/ext/matrix_double3x2.hpp \
		../glm/detail/type_mat3x2.hpp \
		../glm/detail/type_mat3x2.inl \
		../glm/ext/matrix_double3x2_precision.hpp \
		../glm/ext/matrix_float3x2.hpp \
		../glm/ext/matrix_float3x2_precision.hpp \
		../glm/mat3x3.hpp \
		../glm/ext/matrix_double3x3.hpp \
		../glm/detail/type_mat3x3.hpp \
		../glm/detail/type_mat3x3.inl \
		../glm/ext/matrix_double3x3_precision.hpp \
		../glm/ext/matrix_float3x3.hpp \
		../glm/ext/matrix_float3x3_precision.hpp \
		../glm/mat3x4.hpp \
		../glm/ext/matrix_double3x4.hpp \
		../glm/detail/type_mat3x4.hpp \
		../glm/detail/type_mat3x4.inl \
		../glm/ext/matrix_double3x4_precision.hpp \
		../glm/ext/matrix_float3x4.hpp \
		../glm/ext/matrix_float3x4_precision.hpp \
		../glm/mat4x2.hpp \
		../glm/ext/matrix_double4x2.hpp \
		../glm/detail/type_mat4x2.hpp \
		../glm/detail/type_mat4x2.inl \
		../glm/ext/matrix_double4x2_precision.hpp \
		../glm/ext/matrix_float4x2.hpp \
		../glm/ext/matrix_float4x2_precision.hpp \
		../glm/mat4x3.hpp \
		../glm/ext/matrix_double4x3.hpp \
		../glm/detail/type_mat4x3.hpp \
		../glm/detail/type_mat4x3.inl \
		../glm/ext/matrix_double4x3_precision.hpp \
		../glm/ext/matrix_float4x3.hpp \
		../glm/ext/matrix_float4x3_precision.hpp \
		../glm/mat4x4.hpp \
		../glm/ext/matrix_double4x4.hpp \
		../glm/detail/type_mat4x4.hpp \
		../glm/detail/type_mat4x4.inl \
		../glm/detail/type_mat4x4_simd.inl \
		../glm/ext/matrix_double4x4_precision.hpp \
		../glm/ext/matrix_float4x4.hpp \
		../glm/ext/matrix_float4x4_precision.hpp \
		../glm/detail/func_matrix.inl \
		../glm/geometric.hpp \
		../glm/detail/func_geometric.inl \
		../glm/exponential.hpp \
		../glm/detail/type_vec1.hpp \
		../glm/detail/type_vec1.inl \
		../glm/detail/func_exponential.inl \
		../glm/vector_relational.hpp \
		../glm/detail/func_vector_relational.inl \
		../glm/detail/func_vector_relational_simd.inl \
		../glm/detail/_vectorize.hpp \
		../glm/detail/func_exponential_simd.inl \
		../glm/simd/exponential.h \
		../glm/common.hpp \
		../glm/detail/func_common.inl \
		../glm/detail/compute_common.hpp \
		../glm/detail/func_common_simd.inl \
		../glm/simd/common.h \
		../glm/detail/func_geometric_simd.inl \
		../glm/simd/geometric.h \
		../glm/detail/func_matrix_simd.inl \
		../glm/simd/matrix.h \
		../glm/ext/matrix_double2x2_precision.hpp \
		../glm/ext/matrix_float2x2.hpp \
		../glm/ext/matrix_float2x2_precision.hpp \
		../glm/trigonometric.hpp \
		../glm/detail/func_trigonometric.inl \
		../glm/detail/func_trigonometric_simd.inl \
		../glm/packing.hpp \
		../glm/detail/func_packing.inl \
		../glm/detail/type_half.hpp \
		../glm/detail/type_half.inl \
		../glm/detail/func_packing_simd.inl \
		../glm/integer.hpp \
		../glm/detail/func_integer.inl \
		../glm/detail/func_integer_simd.inl \
		../glm/simd/integer.h \
		../glm/gtc/matrix_transform.hpp \
		../glm/ext/matrix_projection.hpp \
		../glm/gtc/constants.hpp \
		../glm/ext/scalar_constants.hpp \
		../glm/ext/scalar_constants.inl \
		../glm/gtc/constants.inl \
		../glm/ext/matrix_projection.inl \
		../glm/ext/matrix_clip_space.hpp \
		../glm/ext/matrix_clip_space.inl \
		../glm/ext/matrix_transform.hpp \
		../glm/gtc/matrix_transform.inl \
		Cloth.h \
		PointMass.h \
		../glm/gtc/type_ptr.hpp \
		../glm/gtc/quaternion.hpp \
		../glm/ext/vector_relational.hpp \
		../glm/ext/vector_relational.inl \
		../glm/detail/type_float.hpp \
		../glm/ext/quaternion_common.hpp \
		../glm/ext/quaternion_geometric.hpp \
		../glm/ext/quaternion_geometric.inl \
		../glm/ext/quaternion_common.inl \
		../glm/ext/quaternion_common_simd.inl \
		../glm/ext/quaternion_float.hpp \
		../glm/detail/type_quat.hpp \
		../glm/ext/quaternion_relational.hpp \
		../glm/ext/quaternion_relational.inl \
		../glm/detail/type_quat.inl \
		../glm/detail/type_quat_simd.inl \
		../glm/ext/quaternion_float_precision.hpp \
		../glm/ext/quaternion_double.hpp \
		../glm/ext/quaternion_double_precision.hpp \
		../glm/ext/quaternion_trigonometric.hpp \
		../glm/ext/quaternion_trigonometric.inl \
		../glm/ext/quaternion_transform.hpp \
		../glm/ext/quaternion_transform.inl \
		../glm/gtc/quaternion.inl \
		../glm/gtc/epsilon.hpp \
		../glm/gtc/epsilon.inl \
		../glm/gtc/quaternion_simd.inl \
		../glm/gtc/vec1.hpp \
		../glm/ext/vector_bool1.hpp \
		../glm/ext/vector_bool1_precision.hpp \
		../glm/ext/vector_float1.hpp \
		../glm/ext/vector_float1_precision.hpp \
		../glm/ext/vector_double1.hpp \
		../glm/ext/vector_double1_precision.hpp \
		../glm/ext/vector_int1.hpp \
		../glm/ext/vector_int1_precision.hpp \
		../glm/ext/vector_uint1.hpp \
		../glm/ext/vector_uint1_precision.hpp \
		../glm/gtc/type_ptr.inl \
		Spring.h \
		Wind.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Simulation.o Simulation.cpp

Spring.o: Spring.cpp Spring.h \
		Cartesian3.h \
		camera.h \
		../glm/glm.hpp \
		../glm/detail/_fixes.hpp \
		../glm/detail/setup.hpp \
		../glm/simd/platform.h \
		../glm/simd/neon.h \
		../glm/fwd.hpp \
		../glm/detail/qualifier.hpp \
		../glm/vec2.hpp \
		../glm/ext/vector_bool2.hpp \
		../glm/detail/type_vec2.hpp \
		../glm/detail/_swizzle.hpp \
		../glm/detail/_swizzle_func.hpp \
		../glm/detail/type_vec2.inl \
		../glm/detail/compute_vector_relational.hpp \
		../glm/ext/vector_bool2_precision.hpp \
		../glm/ext/vector_float2.hpp \
		../glm/ext/vector_float2_precision.hpp \
		../glm/ext/vector_double2.hpp \
		../glm/ext/vector_double2_precision.hpp \
		../glm/ext/vector_int2.hpp \
		../glm/ext/vector_int2_precision.hpp \
		../glm/ext/vector_uint2.hpp \
		../glm/ext/vector_uint2_precision.hpp \
		../glm/vec3.hpp \
		../glm/ext/vector_bool3.hpp \
		../glm/detail/type_vec3.hpp \
		../glm/detail/type_vec3.inl \
		../glm/ext/vector_bool3_precision.hpp \
		../glm/ext/vector_float3.hpp \
		../glm/ext/vector_float3_precision.hpp \
		../glm/ext/vector_double3.hpp \
		../glm/ext/vector_double3_precision.hpp \
		../glm/ext/vector_int3.hpp \
		../glm/ext/vector_int3_precision.hpp \
		../glm/ext/vector_uint3.hpp \
		../glm/ext/vector_uint3_precision.hpp \
		../glm/vec4.hpp \
		../glm/ext/vector_bool4.hpp \
		../glm/detail/type_vec4.hpp \
		../glm/detail/type_vec4.inl \
		../glm/detail/type_vec4_simd.inl \
		../glm/ext/vector_bool4_precision.hpp \
		../glm/ext/vector_float4.hpp \
		../glm/ext/vector_float4_precision.hpp \
		../glm/ext/vector_double4.hpp \
		../glm/ext/vector_double4_precision.hpp \
		../glm/ext/vector_int4.hpp \
		../glm/ext/vector_int4_precision.hpp \
		../glm/ext/vector_uint4.hpp \
		../glm/ext/vector_uint4_precision.hpp \
		../glm/mat2x2.hpp \
		../glm/ext/matrix_double2x2.hpp \
		../glm/detail/type_mat2x2.hpp \
		../glm/detail/type_mat2x2.inl \
		../glm/matrix.hpp \
		../glm/mat2x3.hpp \
		../glm/ext/matrix_double2x3.hpp \
		../glm/detail/type_mat2x3.hpp \
		../glm/detail/type_mat2x3.inl \
		../glm/ext/matrix_double2x3_precision.hpp \
		../glm/ext/matrix_float2x3.hpp \
		../glm/ext/matrix_float2x3_precision.hpp \
		../glm/mat2x4.hpp \
		../glm/ext/matrix_double2x4.hpp \
		../glm/detail/type_mat2x4.hpp \
		../glm/detail/type_mat2x4.inl \
		../glm/ext/matrix_double2x4_precision.hpp \
		../glm/ext/matrix_float2x4.hpp \
		../glm/ext/matrix_float2x4_precision.hpp \
		../glm/mat3x2.hpp \
		../glm/ext/matrix_double3x2.hpp \
		../glm/detail/type_mat3x2.hpp \
		../glm/detail/type_mat3x2.inl \
		../glm/ext/matrix_double3x2_precision.hpp \
		../glm/ext/matrix_float3x2.hpp \
		../glm/ext/matrix_float3x2_precision.hpp \
		../glm/mat3x3.hpp \
		../glm/ext/matrix_double3x3.hpp \
		../glm/detail/type_mat3x3.hpp \
		../glm/detail/type_mat3x3.inl \
		../glm/ext/matrix_double3x3_precision.hpp \
		../glm/ext/matrix_float3x3.hpp \
		../glm/ext/matrix_float3x3_precision.hpp \
		../glm/mat3x4.hpp \
		../glm/ext/matrix_double3x4.hpp \
		../glm/detail/type_mat3x4.hpp \
		../glm/detail/type_mat3x4.inl \
		../glm/ext/matrix_double3x4_precision.hpp \
		../glm/ext/matrix_float3x4.hpp \
		../glm/ext/matrix_float3x4_precision.hpp \
		../glm/mat4x2.hpp \
		../glm/ext/matrix_double4x2.hpp \
		../glm/detail/type_mat4x2.hpp \
		../glm/detail/type_mat4x2.inl \
		../glm/ext/matrix_double4x2_precision.hpp \
		../glm/ext/matrix_float4x2.hpp \
		../glm/ext/matrix_float4x2_precision.hpp \
		../glm/mat4x3.hpp \
		../glm/ext/matrix_double4x3.hpp \
		../glm/detail/type_mat4x3.hpp \
		../glm/detail/type_mat4x3.inl \
		../glm/ext/matrix_double4x3_precision.hpp \
		../glm/ext/matrix_float4x3.hpp \
		../glm/ext/matrix_float4x3_precision.hpp \
		../glm/mat4x4.hpp \
		../glm/ext/matrix_double4x4.hpp \
		../glm/detail/type_mat4x4.hpp \
		../glm/detail/type_mat4x4.inl \
		../glm/detail/type_mat4x4_simd.inl \
		../glm/ext/matrix_double4x4_precision.hpp \
		../glm/ext/matrix_float4x4.hpp \
		../glm/ext/matrix_float4x4_precision.hpp \
		../glm/detail/func_matrix.inl \
		../glm/geometric.hpp \
		../glm/detail/func_geometric.inl \
		../glm/exponential.hpp \
		../glm/detail/type_vec1.hpp \
		../glm/detail/type_vec1.inl \
		../glm/detail/func_exponential.inl \
		../glm/vector_relational.hpp \
		../glm/detail/func_vector_relational.inl \
		../glm/detail/func_vector_relational_simd.inl \
		../glm/detail/_vectorize.hpp \
		../glm/detail/func_exponential_simd.inl \
		../glm/simd/exponential.h \
		../glm/common.hpp \
		../glm/detail/func_common.inl \
		../glm/detail/compute_common.hpp \
		../glm/detail/func_common_simd.inl \
		../glm/simd/common.h \
		../glm/detail/func_geometric_simd.inl \
		../glm/simd/geometric.h \
		../glm/detail/func_matrix_simd.inl \
		../glm/simd/matrix.h \
		../glm/ext/matrix_double2x2_precision.hpp \
		../glm/ext/matrix_float2x2.hpp \
		../glm/ext/matrix_float2x2_precision.hpp \
		../glm/trigonometric.hpp \
		../glm/detail/func_trigonometric.inl \
		../glm/detail/func_trigonometric_simd.inl \
		../glm/packing.hpp \
		../glm/detail/func_packing.inl \
		../glm/detail/type_half.hpp \
		../glm/detail/type_half.inl \
		../glm/detail/func_packing_simd.inl \
		../glm/integer.hpp \
		../glm/detail/func_integer.inl \
		../glm/detail/func_integer_simd.inl \
		../glm/simd/integer.h \
		../glm/gtc/matrix_transform.hpp \
		../glm/ext/matrix_projection.hpp \
		../glm/gtc/constants.hpp \
		../glm/ext/scalar_constants.hpp \
		../glm/ext/scalar_constants.inl \
		../glm/gtc/constants.inl \
		../glm/ext/matrix_projection.inl \
		../glm/ext/matrix_clip_space.hpp \
		../glm/ext/matrix_clip_space.inl \
		../glm/ext/matrix_transform.hpp \
		../glm/gtc/matrix_transform.inl \
		PointMass.h \
		../glm/gtc/type_ptr.hpp \
		../glm/gtc/quaternion.hpp \
		../glm/ext/vector_relational.hpp \
		../glm/ext/vector_relational.inl \
		../glm/detail/type_float.hpp \
		../glm/ext/quaternion_common.hpp \
		../glm/ext/quaternion_geometric.hpp \
		../glm/ext/quaternion_geometric.inl \
		../glm/ext/quaternion_common.inl \
		../glm/ext/quaternion_common_simd.inl \
		../glm/ext/quaternion_float.hpp \
		../glm/detail/type_quat.hpp \
		../glm/ext/quaternion_relational.hpp \
		../glm/ext/quaternion_relational.inl \
		../glm/detail/type_quat.inl \
		../glm/detail/type_quat_simd.inl \
		../glm/ext/quaternion_float_precision.hpp \
		../glm/ext/quaternion_double.hpp \
		../glm/ext/quaternion_double_precision.hpp \
		../glm/ext/quaternion_trigonometric.hpp \
		../glm/ext/quaternion_trigonometric.inl \
		../glm/ext/quaternion_transform.hpp \
		../glm/ext/quaternion_transform.inl \
		../glm/gtc/quaternion.inl \
		../glm/gtc/epsilon.hpp \
		../glm/gtc/epsilon.inl \
		../glm/gtc/quaternion_simd.inl \
		../glm/gtc/vec1.hpp \
		../glm/ext/vector_bool1.hpp \
		../glm/ext/vector_bool1_precision.hpp \
		../glm/ext/vector_float1.hpp \
		../glm/ext/vector_float1_precision.hpp \
		../glm/ext/vector_double1.hpp \
		../glm/ext/vector_double1_precision.hpp \
		../glm/ext/vector_int1.hpp \
		../glm/ext/vector_int1_precision.hpp \
		../glm/ext/vector_uint1.hpp \
		../glm/ext/vector_uint1_precision.hpp \
		../glm/gtc/type_ptr.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Spring.o Spring.cpp

Wind.o: Wind.cpp Wind.h \
		Cartesian3.h \
		camera.h \
		../glm/glm.hpp \
		../glm/detail/_fixes.hpp \
		../glm/detail/setup.hpp \
		../glm/simd/platform.h \
		../glm/simd/neon.h \
		../glm/fwd.hpp \
		../glm/detail/qualifier.hpp \
		../glm/vec2.hpp \
		../glm/ext/vector_bool2.hpp \
		../glm/detail/type_vec2.hpp \
		../glm/detail/_swizzle.hpp \
		../glm/detail/_swizzle_func.hpp \
		../glm/detail/type_vec2.inl \
		../glm/detail/compute_vector_relational.hpp \
		../glm/ext/vector_bool2_precision.hpp \
		../glm/ext/vector_float2.hpp \
		../glm/ext/vector_float2_precision.hpp \
		../glm/ext/vector_double2.hpp \
		../glm/ext/vector_double2_precision.hpp \
		../glm/ext/vector_int2.hpp \
		../glm/ext/vector_int2_precision.hpp \
		../glm/ext/vector_uint2.hpp \
		../glm/ext/vector_uint2_precision.hpp \
		../glm/vec3.hpp \
		../glm/ext/vector_bool3.hpp \
		../glm/detail/type_vec3.hpp \
		../glm/detail/type_vec3.inl \
		../glm/ext/vector_bool3_precision.hpp \
		../glm/ext/vector_float3.hpp \
		../glm/ext/vector_float3_precision.hpp \
		../glm/ext/vector_double3.hpp \
		../glm/ext/vector_double3_precision.hpp \
		../glm/ext/vector_int3.hpp \
		../glm/ext/vector_int3_precision.hpp \
		../glm/ext/vector_uint3.hpp \
		../glm/ext/vector_uint3_precision.hpp \
		../glm/vec4.hpp \
		../glm/ext/vector_bool4.hpp \
		../glm/detail/type_vec4.hpp \
		../glm/detail/type_vec4.inl \
		../glm/detail/type_vec4_simd.inl \
		../glm/ext/vector_bool4_precision.hpp \
		../glm/ext/vector_float4.hpp \
		../glm/ext/vector_float4_precision.hpp \
		../glm/ext/vector_double4.hpp \
		../glm/ext/vector_double4_precision.hpp \
		../glm/ext/vector_int4.hpp \
		../glm/ext/vector_int4_precision.hpp \
		../glm/ext/vector_uint4.hpp \
		../glm/ext/vector_uint4_precision.hpp \
		../glm/mat2x2.hpp \
		../glm/ext/matrix_double2x2.hpp \
		../glm/detail/type_mat2x2.hpp \
		../glm/detail/type_mat2x2.inl \
		../glm/matrix.hpp \
		../glm/mat2x3.hpp \
		../glm/ext/matrix_double2x3.hpp \
		../glm/detail/type_mat2x3.hpp \
		../glm/detail/type_mat2x3.inl \
		../glm/ext/matrix_double2x3_precision.hpp \
		../glm/ext/matrix_float2x3.hpp \
		../glm/ext/matrix_float2x3_precision.hpp \
		../glm/mat2x4.hpp \
		../glm/ext/matrix_double2x4.hpp \
		../glm/detail/type_mat2x4.hpp \
		../glm/detail/type_mat2x4.inl \
		../glm/ext/matrix_double2x4_precision.hpp \
		../glm/ext/matrix_float2x4.hpp \
		../glm/ext/matrix_float2x4_precision.hpp \
		../glm/mat3x2.hpp \
		../glm/ext/matrix_double3x2.hpp \
		../glm/detail/type_mat3x2.hpp \
		../glm/detail/type_mat3x2.inl \
		../glm/ext/matrix_double3x2_precision.hpp \
		../glm/ext/matrix_float3x2.hpp \
		../glm/ext/matrix_float3x2_precision.hpp \
		../glm/mat3x3.hpp \
		../glm/ext/matrix_double3x3.hpp \
		../glm/detail/type_mat3x3.hpp \
		../glm/detail/type_mat3x3.inl \
		../glm/ext/matrix_double3x3_precision.hpp \
		../glm/ext/matrix_float3x3.hpp \
		../glm/ext/matrix_float3x3_precision.hpp \
		../glm/mat3x4.hpp \
		../glm/ext/matrix_double3x4.hpp \
		../glm/detail/type_mat3x4.hpp \
		../glm/detail/type_mat3x4.inl \
		../glm/ext/matrix_double3x4_precision.hpp \
		../glm/ext/matrix_float3x4.hpp \
		../glm/ext/matrix_float3x4_precision.hpp \
		../glm/mat4x2.hpp \
		../glm/ext/matrix_double4x2.hpp \
		../glm/detail/type_mat4x2.hpp \
		../glm/detail/type_mat4x2.inl \
		../glm/ext/matrix_double4x2_precision.hpp \
		../glm/ext/matrix_float4x2.hpp \
		../glm/ext/matrix_float4x2_precision.hpp \
		../glm/mat4x3.hpp \
		../glm/ext/matrix_double4x3.hpp \
		../glm/detail/type_mat4x3.hpp \
		../glm/detail/type_mat4x3.inl \
		../glm/ext/matrix_double4x3_precision.hpp \
		../glm/ext/matrix_float4x3.hpp \
		../glm/ext/matrix_float4x3_precision.hpp \
		../glm/mat4x4.hpp \
		../glm/ext/matrix_double4x4.hpp \
		../glm/detail/type_mat4x4.hpp \
		../glm/detail/type_mat4x4.inl \
		../glm/detail/type_mat4x4_simd.inl \
		../glm/ext/matrix_double4x4_precision.hpp \
		../glm/ext/matrix_float4x4.hpp \
		../glm/ext/matrix_float4x4_precision.hpp \
		../glm/detail/func_matrix.inl \
		../glm/geometric.hpp \
		../glm/detail/func_geometric.inl \
		../glm/exponential.hpp \
		../glm/detail/type_vec1.hpp \
		../glm/detail/type_vec1.inl \
		../glm/detail/func_exponential.inl \
		../glm/vector_relational.hpp \
		../glm/detail/func_vector_relational.inl \
		../glm/detail/func_vector_relational_simd.inl \
		../glm/detail/_vectorize.hpp \
		../glm/detail/func_exponential_simd.inl \
		../glm/simd/exponential.h \
		../glm/common.hpp \
		../glm/detail/func_common.inl \
		../glm/detail/compute_common.hpp \
		../glm/detail/func_common_simd.inl \
		../glm/simd/common.h \
		../glm/detail/func_geometric_simd.inl \
		../glm/simd/geometric.h \
		../glm/detail/func_matrix_simd.inl \
		../glm/simd/matrix.h \
		../glm/ext/matrix_double2x2_precision.hpp \
		../glm/ext/matrix_float2x2.hpp \
		../glm/ext/matrix_float2x2_precision.hpp \
		../glm/trigonometric.hpp \
		../glm/detail/func_trigonometric.inl \
		../glm/detail/func_trigonometric_simd.inl \
		../glm/packing.hpp \
		../glm/detail/func_packing.inl \
		../glm/detail/type_half.hpp \
		../glm/detail/type_half.inl \
		../glm/detail/func_packing_simd.inl \
		../glm/integer.hpp \
		../glm/detail/func_integer.inl \
		../glm/detail/func_integer_simd.inl \
		../glm/simd/integer.h \
		../glm/gtc/matrix_transform.hpp \
		../glm/ext/matrix_projection.hpp \
		../glm/gtc/constants.hpp \
		../glm/ext/scalar_constants.hpp \
		../glm/ext/scalar_constants.inl \
		../glm/gtc/constants.inl \
		../glm/ext/matrix_projection.inl \
		../glm/ext/matrix_clip_space.hpp \
		../glm/ext/matrix_clip_space.inl \
		../glm/ext/matrix_transform.hpp \
		../glm/gtc/matrix_transform.inl \
		PointMass.h \
		../glm/gtc/type_ptr.hpp \
		../glm/gtc/quaternion.hpp \
		../glm/ext/vector_relational.hpp \
		../glm/ext/vector_relational.inl \
		../glm/detail/type_float.hpp \
		../glm/ext/quaternion_common.hpp \
		../glm/ext/quaternion_geometric.hpp \
		../glm/ext/quaternion_geometric.inl \
		../glm/ext/quaternion_common.inl \
		../glm/ext/quaternion_common_simd.inl \
		../glm/ext/quaternion_float.hpp \
		../glm/detail/type_quat.hpp \
		../glm/ext/quaternion_relational.hpp \
		../glm/ext/quaternion_relational.inl \
		../glm/detail/type_quat.inl \
		../glm/detail/type_quat_simd.inl \
		../glm/ext/quaternion_float_precision.hpp \
		../glm/ext/quaternion_double.hpp \
		../glm/ext/quaternion_double_precision.hpp \
		../glm/ext/quaternion_trigonometric.hpp \
		../glm/ext/quaternion_trigonometric.inl \
		../glm/ext/quaternion_transform.hpp \
		../glm/ext/quaternion_transform.inl \
		../glm/gtc/quaternion.inl \
		../glm/gtc/epsilon.hpp \
		../glm/gtc/epsilon.inl \
		../glm/gtc/quaternion_simd.inl \
		../glm/gtc/vec1.hpp \
		../glm/ext/vector_bool1.hpp \
		../glm/ext/vector_bool1_precision.hpp \
		../glm/ext/vector_float1.hpp \
		../glm/ext/vector_float1_precision.hpp \
		../glm/ext/vector_double1.hpp \
		../glm/ext/vector_double1_precision.hpp \
		../glm/ext/vector_int1.hpp \
		../glm/ext/vector_int1_precision.hpp \
		../glm/ext/vector_uint1.hpp \
		../glm/ext/vector_uint1_precision.hpp \
		../glm/gtc/type_ptr.inl \
		Spring.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Wind.o Wind.cpp

moc_MasterWidget.o: moc_MasterWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MasterWidget.o moc_MasterWidget.cpp

moc_RenderWidget.o: moc_RenderWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_RenderWidget.o moc_RenderWidget.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

